### ISSUE TITLE
GoogleAdsException has no InnerException with the original exception

### ISSUE THREAD

**Issue by Zweitze** [googleads/google-ads-dotnet#10]
Reproduction: Modify example GetKeyworkStats.cs, modify one of the select-fields (I changed "campaign.id" to "campaign.id__". You get a GoogleAdsException.
This exception has no reference to the original network exception, at least its InnerException member is null.

Note I used them to communicate with AdWords API Support to give more insights in the background. AdWords API used to pass the inner HttpWebException, and we passed its Response headers to AdWords API Support. Those headers contained extra information like the actual server name that generated the response.

However, if such information is not at all usable for support this issue can be closed.

**Comment by AnashOommen** [comment]
Thanks Zwitze, please keep those bugs coming!

**Comment by AnashOommen** [comment]
Google Ads APIs use gRPC, and is hence built on top of the Google's gRPC libraries. They don't pass the underlying HTTP2 error to the consuming layer, so there's not much useful information that can be exposed to the end user.

I'll add logging in an upcoming release, and the library already exposes requestIds. Combined, that should be a reasonable substitute for most cases.

gRPC exposes low level logging, which you can turn on by using

Setting two environment variables, `GRPC_TRACE=all` and `GRPC_VERBOSITY=debug`
Calling `GrpcEnvironment.SetLogger` in your code, e.g. `GrpcEnvironment.SetLogger(new ConsoleLogger())` with suitable using directives.

All the grpc environment variables are [here](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md), but that log has so much details in there that it turns useless for anything other than trivial cases.

I'll keep this bug open for now; I realize that all these details make more sense in a wiki for discovery. I'll close it once the wiki is updated, but feel free to reopen if you feel this is a major issue that gets in the way of your development cycles, and share your specific use case. I'll talk to the gRPC team to see what can be done.

**Comment by AnashOommen** [comment]
This is now documented in the README.md, so marking this as fixed.
