### ISSUE TITLE
Exception Thrown in Google.Ads.GoogleAds.Logging.LoggingInterceptor (2.2)

### ISSUE THREAD

**Issue by aukevin** [googleads/google-ads-dotnet#108]
I started getting an exception thrown from the LoggingInterceptor when I upgraded from 2.0 to 2.2. I think it might be related to this change made in 2.1:

>- Made a change to generate logs only if appropriate logging levels are set.

To generate the logs, I had set:
`TraceUtilities.Configure(TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE, listener, SourceLevels.All);`
`TraceUtilities.Configure(TraceUtilities.SUMMARY_REQUEST_LOGS_SOURCE, listener, SourceLevels.All);`

Is anyone else having this issue?

**Comment by AnashOommen** [comment]
I think this was related to the partial failure support I added. I'll try getting in a fix in the next release.

**Comment by AnashOommen** [comment]
This should be fixed in the latest release.
