### ISSUE TITLE
requestId is only available when an exception occurs

### ISSUE THREAD

**Issue by Zweitze** [googleads/google-ads-dotnet#11]
In the library classes, only the exceptions do expose requestId (Well, I checked CustomerService and GoogleAdsService, but I assume this is for other classes also the case). I am pretty sure requestId is also available for calls that did NOT result in an Exception.

Still we want to learn it, log it, and use it to communicate with Ads API when we have questions about a result. Further we may need few similar attributes, like server response time and operation count.

**Comment by Zweitze** [comment]
To get an idea for a solution, look at Analytics Reporting API v3. [The response](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#data_response) is a structure, with: 
- Field "rows" with the actual result of the API call
- Field "query" with the request
- Many other fields, like the view to which the call was made

When following this example, all responses of Ads API will lead to a structure, each with fields like requestId, number of operations, maybe the request, and a field with the data that was requested.

**Comment by AnashOommen** [comment]
Hi Zwitze,

I think the difference here is due the way in which the Analytics Reporting API was designed, v/s GoogleAds API was designed.

The important part around this discussion is that Google Ads API is a grpc API, and grpc allows two ways to return metadata from servers.

1. You return the metadata as part of the response, like the way Analytics API does.
2. You return the metadata in a metadata header. (Similar concept as HTTP headers in HTTP 1/1).

Google Ads API went with the second choice, so you could get back the metadata in normal responses also, like this:

```c#
GoogleAdsResponseMetadata metadata = new GoogleAdsResponseMetadata(client.Config);

// Add the campaigns.
    MutateCampaignsResponse retVal = campaignService.MutateCampaigns(
        customerId.ToString(), operations.ToArray(), metadata.CallSettings);
```
Right now, only the requestId is exposed this way, but we plan to release other metadata fields that are available in AdWords API as we get closer to feature parity.

I'll update the wiki guide with more details on client library usage, it's a task that has been overdue from my end.

**Comment by AnashOommen** [comment]
This is now documented in the README.md.
