### ISSUE TITLE
Enable logging

### ISSUE THREAD

**Issue by RentCafeDev** [googleads/google-ads-dotnet#111]
I have tried to enable logging by adding the following to my code:

// Detailed logs.
TraceUtilities.Configure(TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE,
    "C:\\logs\\details.log", System.Diagnostics.SourceLevels.All);

// Summary logs.
TraceUtilities.Configure(TraceUtilities.SUMMARY_REQUEST_LOGS_SOURCE,
    "C:\\logs\\summary.log", System.Diagnostics.SourceLevels.All);

The above is from the following link:
https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging

The log files are created but nothing is written to the logs.  
Am I missing something?

KDJ

**Comment by wihl** [comment]
Please update to the latest version of this library and follow the instructions in the README. V1_0 does not logging.

**Comment by AnashOommen** [comment]
I'm closing this issue as not replicable. If the issue persists, please feel free to reopen.
