### ISSUE TITLE
Keyword Planner keyword forecast

### ISSUE THREAD

**Issue by sqreem-geno** [googleads/google-ads-dotnet#112]
Keyword planner keyword forecast and historical produces different value compared to the one shown in Google Ads website. 

What should be the KeywordPlanCampaign.CpcBidMicro value set to? 

What is its currency? Is it default to the account currency settings?

I think that some of my questions mentioned are the factor that produces the difference in values.

**Comment by AnashOommen** [comment]
Since this issue is not specific to the librry, could you post on https://groups.google.com/forum/#!forum/adwords-api ?
