### ISSUE TITLE
Minor:Example exe usage message shows assembly name and  can be more clear to user

### ISSUE THREAD

**Issue by bilalagha** [googleads/google-ads-dotnet#117]
Running example exe without example name display below usage example message, which can be more clear, the the assembly name displayed instead of exe name , also , Instead of supported examples , supported example names would be more clearer as matching with the above usage string

===============  usage example  message ========================
Runs Google Ads API code examples
Usage : Google.Ads.GoogleAds.Examples, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null examplename [flags]

Supported examples:

V2.AddAccountBudgetProposal : This code example creates an account budget proposal using the 'CREATE' operation. To get account budget proposals, run GetAccountBudgetProposals.cs.
V2.AddAdGroup : This code example illustrates how to create ad groups. To create campaigns, run AddCampaigns.cs
V2.AddAdGroupBidModifier : This code example demonstrates how to add an ad group bid modifier for mobile devices. To get ad group bid modifiers, see GetAdGroupBidModifiers.cs.
V2.AddCampaignBidModifier : This code example demonstrates how to add a campaign-level bid modifier for call interactions.
V2.AddCampaignDraft : This code example adds a campaign draft for a campaign. Make sure you specify a campaign that has a budget with explicitly_shared set to false.

**Comment by AnashOommen** [comment]
If you are interested in contributing, feel free to send me a pull request :-)

**Comment by bilalagha** [comment]
> you are interested in contributing, feel free to send me a pull request :-)

Sure, Will do it
Thanks
Bilal

**Comment by AnashOommen** [comment]
Fixed in v2.7.0.
