### ISSUE TITLE
GoogleAdsClient always generates new access token

### ISSUE THREAD

**Issue by AdrianPell** [googleads/google-ads-dotnet#118]
In the Google Adwords API, there was a callback in the authentication flow (on OAuth2ProviderForApplications) which would be called whenever an access token was refreshed, and also a call to refresh the access token if needed. We used this because we made many independent calls to the Adwords API and cached the access token to avoid the overhead of refreshing.

In the Google Ads API, it seems that the implemented behavior is to always start by obtaining an access token from the given refresh token. Indeed, any access token passed into the client through the GoogleAdsConfig is ignored with only the refresh token used to initialize the UserCredential.

Furthermore, there's no way to hook the activity on the UserCredential because only an ICredential is exposed, and I can't override this because there's no available interface on GoogleAdsConfig.

So ...

1) Is it reasonable to refresh access tokens frequently? What's the overhead (presumably at least a server round-trip)? In our case, we might be doing this many, many times as the clients are created in Azure functions ... It's even possible that many of these refreshed access tokens might be used concurrently. Is that a problem?
2) Alternatively, is there a way to hook that refresh activity?

**Comment by AdrianPell** [comment]
@AnashOommen Any thoughts on this one?

**Comment by AnashOommen** [comment]
Hi Adrian,

I'll get you a fix for this issue in the next push.

**Comment by AdrianPell** [comment]
Thanks Anash!

**Comment by AnashOommen** [comment]
Hi Adrian,

With v2.7.0, you should be able to extend `GoogleAdsConfig` class and add your own logic for refreshing credentials. Let me know if that works for you.
