### ISSUE TITLE
invalid_client error when using service account + domain wide delegation to authenticate

### ISSUE THREAD

**Issue by tylerfoulkes** [googleads/google-ads-dotnet#119]
I am trying to authenticate into Google Ads using this API client. I am trying to authenticate using a service account + gsuite domain wide delegation. I have performed all of the steps in [this](https://developers.google.com/google-ads/api/docs/oauth/service-accounts) documentation but am receiving an invalid_client error from Google. Below is the code I am running.
```cs
GoogleAdsClient client = new GoogleAdsClient();
client.Config.OAuth2Mode = OAuth2Flow.SERVICE_ACCOUNT;
client.Config.OAuth2PrnEmail = "useremail@gsuite.com";
client.Config.OAuth2ClientId = "serviceaccountclientid";
client.Config.OAuth2SecretsJsonPath = HostingEnvironment.MapPath("~/service-account-keys-downloaded-from-gcp.json");
var svc = client.GetService(Services.V2.CustomerService);
var accounts = svc.ListAccessibleCustomers();
```
The code is supposed to authenticate on behalf of a user in a gsuite organization and list all of the accounts the user has access to. When I run the above code I get the following error.
```
Status(StatusCode=Unavailable, Detail="Getting metadata from plugin
failed with error: Exception occurred in metadata credentials plugin.
Google.Apis.Auth.OAuth2.Responses.TokenResponseException:
Error:"invalid_client", Description:"The OAuth client was not found.", Uri:""
```
It seems that no matter what email I try to authenticate with I still get the same error which makes me think that there is a fundamental issue with how I am trying to authenticate.

All of the necessary fields seem to map properly into the GoogleAdsClient Config except for the client secret. I am unable to pass a client secret into the request because the service account client (auto created when enabling domain wide delegation on a service account in GCP) does not come furnished with a client secret. The docs that I have mentioned don't seem to specify how you would obtain a client secret when authenticating with a Google service account.

**Comment by AnashOommen** [comment]
Try setting a breakpoint on the line where you get the svc. See if (1) the json was loaded correctly into config and (2) that’s the correct client Id you whitelisted in your gsuite domain. That’s the primary suspect.

**Comment by tylerfoulkes** [comment]
@AnashOommen Yes the config object in the svc is populated with all of the values that I would expect. Below are the config fields that are populated correctly to my knowledge, am I missing something?
`OAuth2ClientId`
`OAuth2Mode`
`OAuth2PrivateKey`
`OAuth2PrnEmail`
`OAuth2ServiceAccountEmail`
`OAuth2Scope`

**Comment by tylerfoulkes** [comment]
@AnashOommen Is there anything else that I could potentially be missing?

**Comment by AnashOommen** [comment]
Hi Tyler, is this issue resolved for you?

**Comment by tylerfoulkes** [comment]
@AnashOommen I was not able to get the `SERVICE_ACCOUNT` authentication working so I tried switching to `APPLICATION` auth and I am still experiencing the same `invalid_client` error. My code is below.

```csharp
var settings = new Dictionary<string, string>
 {
      { "OAuth2Mode", "APPLICATION" },
      { "AuthorizationMethod", "OAuth2"},
      { "OAuth2RefreshToken", usergooglerefreshtoken },
      { "OAuth2ClientId", oauthclientid },
      { "OAuth2ClientSecret", oauthclientsecret },
      { "DeveloperToken", developertoken }
};
var config = new GoogleAdsConfig(settings);
GoogleAdsClient client = new GoogleAdsClient(config);
var svc = client.GetService(Services.V3.CustomerService);
var test = svc.ListAccessibleCustomers();
```

I have tried creating a new project in GCP and generating new client/secret values and I still get the same `invalid_client` error when I run the above code.

**Comment by tylerfoulkes** [comment]
It seems to be working now, although I am not sure what I tweaked to get it working.

**Comment by fsutanto88** [comment]
> It seems to be working now, although I am not sure what I tweaked to get it working.

Hi Tyler, were you able to work with the service account or the application OAuth2?

**Comment by tylerfoulkes** [comment]
@fsutanto88 I wasn't able to get the service account authentication working but I was able to get the standard application OAuth2 flow working.
