### ISSUE TITLE
Upgrade to gRPC C# 2.x

### ISSUE THREAD

**Issue by jtattermusch** [googleads/google-ads-dotnet#120]
Context: https://github.com/grpc/proposal/blob/master/L57-csharp-new-major-version.md

The ads client libraries should upgrade to gRPC C# 2.x at some point. There's no functional changes, you just need to upgrade the Grpc.Core nuget and rebuild. Details are in the link above.

Please provide the ETA of making the switch (if already known).

**Comment by AnashOommen** [comment]
We are blocked on lack of artman support, it still generates code for v1.10 of grpc. They don’t have any immediate plans due to the amount of work involved in doing so.

See b/140880645 for an internal discussion.

**Comment by AnashOommen** [comment]
Fixed in 3.0.0.
