### ISSUE TITLE
GetCampaign.cs is not returning ALL Campaigns of customer.

### ISSUE THREAD

**Issue by siddharthmishrasm** [googleads/google-ads-dotnet#122]
Firstly I link my customer to my manager account and then I'll try to get the campaigns of the customer from the Api and it's not returning any Campaign although customer have a active smart campaign running, Then I add one more campaign in Customer from Api and try GetCampaign again then it is returning new campaign which I created but the already existing smart campaign is still not returning.

**Comment by AnashOommen** [comment]
Maybe that old type campaign isn't supported in the API. Since this issue is not specific to the librry, could you post on https://groups.google.com/forum/#!forum/adwords-api ?
