### ISSUE TITLE
google-ads-dotnet vs  googleads-dotnet-lib

### ISSUE THREAD

**Issue by tiger2014** [googleads/google-ads-dotnet#152]
If we will create a project to manage our accounts of google ads. Which one should we use?

**Comment by AnashOommen** [comment]
Short answer: You can use either of them.

Long answer:

```googleads-dotnet-lib``` corresponds to the [```AdWords API```](https://developers.google.com/adwords/api/docs/guides/start). This is the API that's widely used by developers right now.

```google-ads-dotnet``` corresponds to the [```Google Ads API```](https://developers.google.com/google-ads/api/docs/start). This API is the next iteration of the ```AdWords API```. It is in beta now, and is largely feature complete, but there are still features that are missing in it compared to ```AdWords API```. 

At some point in the future, ```AdWords API``` will be shut down, and ```Google Ads API``` will become the preferred API. But no dates have been announced for it.

My recommendation is to visit the [forum](https://groups.google.com/g/adwords-api) as well as check the documentation to figure out whether all the features you need are available on ```Google Ads API```. If yes, use ```google-ads-dotnet```. If not, use ```googleads-dotnet-lib``` (or a hybrid application) and rewrite the necessary parts with the new API at some future stage.
