### ISSUE TITLE
Docs Feature Request: OfflineUserDataJobService

### ISSUE THREAD

**Issue by brookjim** [googleads/google-ads-dotnet#185]
v2.9.0 client library
4.5.2 .NET framework
Win 10

Services.V3.OfflineUserDataJobService has been added to the latest release. There appears to be no documentation or sample code for use uploading Store Sales conversions (except some gRPC definitions), can someone provide a pointer if there is? I created an uploading app based on a best guess, but it hangs indefinitely on RunOfflineUserDataJob. Is there a release date for docs/samples using OfflineUserDataJobService with SSD? Thanks so much!

**Comment by AnashOommen** [comment]
Hi Brook,

If you have an example that you tried, but didn't work, then feel free to drop an email to googleadsapi-support@google.com and addressed to me. I'll take a look. 

Right now, I don't think there's a code example planned for this feature, but I'll try to get it into the team's list of TODOs for the next quarter.

**Comment by AndrewMBurke** [comment]
A code example for the OfflineUserDataJobService to upload conversion data is currently in internal development. I will update when it is live.

**Comment by AnashOommen** [comment]
Fixed in v4.0.0.
