### ISSUE TITLE
Integrate TraceUtilities logging into something like Kibana or DataDog

### ISSUE THREAD

**Issue by bonniecpk** [googleads/google-ads-dotnet#191]
**Describe the problem you are trying to solve**
I have no idea how to integrate TraceUtilities logging into something like Kibana or DataDog. Can you please provide such feature and documentation on this? 

**Describe the solution you would like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
TraceUtilities is helpful for debugging only. How else can developers use it? Additional documentation about TraceUtilities would be helpful

**Comment by Raibaz** [comment]
Fixed in V14.1.0
