### ISSUE TITLE
googleAdsService.SearchStream response callback doesn't work

### ISSUE THREAD

**Issue by mithun146** [googleads/google-ads-dotnet#197]
I'm trying to get all campaigns by using the below code

`        GoogleAdsServiceClient googleAdsService = client.GetService(Services.V3.GoogleAdsService);

        // Create a query that will retrieve all campaigns.
        string query = @"SELECT
                        campaign.id,
                        campaign.name,
                        campaign.network_settings.target_content_network
                    FROM campaign
                    ORDER BY campaign.id";

        try
        {
            // Issue a search request.
            googleAdsService.SearchStream(customerId.ToString(), query,
                delegate (SearchGoogleAdsStreamResponse resp)
                {
                    foreach (GoogleAdsRow googleAdsRow in resp.Results)
                    {
                        Console.WriteLine("Campaign with ID {0} and name '{1}' was found.",
                            googleAdsRow.Campaign.Id, googleAdsRow.Campaign.Name);
                    }
                    rowResult = resp.Results;
                }
            );

        }
`

the response callback on the googleAdsService.SearchStream method doesn't fire and no error is thrown.

**Comment by AnashOommen** [comment]
Hi Mithun, I wonder if the rowcount being zero is the issue. Let me try.

**Comment by AnashOommen** [comment]
Yep, https://github.com/googleads/google-ads-dotnet/blob/master/src/V3/ServiceHelperMethods.cs#L56 doesn't enter the loop if there are no results.

Perhaps I can modify the code to invoke it at least once, with an empty result?

**Comment by AnashOommen** [comment]
Fixed in v4.0.0.
