### ISSUE TITLE
Call to TraceUtilites.Configure throws an exception occasionally

### ISSUE THREAD

**Issue by vladkuz** [googleads/google-ads-dotnet#201]
**Which version of the client library are you using?**
3.0.0

**Which version of .NET are you using?**
Net Core 3.1

**Which operating system (Linux, Windows, ...) and version?**
Windows 10

**Actions taken**
```
using gacu = Google.Api.Ads.Common.Util;
using gagu = Google.Ads.GoogleAds.Util;

...
API Controller method() {
  ... 
  gacu::TraceUtilities.Configure(gacu::TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE, writer, System.Diagnostics.SourceLevels.All);
  gagu::TraceUtilities.Configure(gagu::TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE, writer, System.Diagnostics.SourceLevels.All);
 ...
}
```

**Expected result**
No exceptions thrown

**Actual result**
Occasional System.InvalidOperationException(Message="Collection was modified; enumeration operation may not execute.")

It is likely this occurs when there are multiple simultaneous requests to the API method that makes the Configure() calls.

StackTrace:

```
at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
at System.Diagnostics.TraceListenerCollection.get_Item(String name)
at Google.Ads.GoogleAds.Util.TraceUtilities.Configure(String source, TraceListener traceListener, SourceLevels levels)`
```

**Comment by AnashOommen** [comment]
Fixed in v4.0.0.
