### ISSUE TITLE
ResourceNames.PaymentsAccount returns malformed resource name

### ISSUE THREAD

**Issue by AndrewMBurke** [googleads/google-ads-dotnet#203]
**Which version of the client library are you using?**
V3

**Which version of .NET are you using?**
.NET Core 3.0

**Which operating system (Linux, Windows, ...) and version?**
Linux

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
Call to ResourceNames.PaymentsAccount(long, long).

**Expected result**
Resource name in the form "customers/XXXYYYZZZ/paymentsAccounts/AAAA-BBBB-CCCC-DDDD"

**Actual result**
Resource name in the form "customers/XXXYYYZZZ/paymentsAccounts/AAAABBBBCCCCDDDD"

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**
N/A

**Comment by AnashOommen** [comment]
Fixed in v4.0.0.
