### ISSUE TITLE
GetAsyncEnumerator() on GoogleAdsRow is not suitable

### ISSUE THREAD

**Issue by ComicalHysteria** [googleads/google-ads-dotnet#223]
**Which version of the client library are you using?**
4.0.0
**Which version of .NET are you using?**
3.1
**Which operating system (Linux, Windows, ...) and version?**
Windows 
**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
`               // Issue the search request.
                PagedAsyncEnumerable<SearchGoogleAdsResponse, GoogleAdsRow> labelResult =
                    googleAdsService.SearchAsync(customerId.ToString(), labelQuery);

                await foreach(var x in labelResult.GetAsyncEnumerator())
                {
                    // can not use async Enumerator
                }`
![image](https://user-images.githubusercontent.com/16730495/90044943-fbbd1e80-dc93-11ea-8454-ec27d595cfa5.png)

**Comment by AnashOommen** [comment]
Try
```
await foreach (var x in labelResult)
{
}
```

I'll get someone to take a closer look as to why the error happens.

**Comment by AnashOommen** [comment]
I confirmed from the Google Cloud SDK team that the previous suggestion is valid. Closing this issue as WAI.
