### ISSUE TITLE
Can you add an example to remove the UserList that's created in AddCustomerMatchUserList.cs ?

### ISSUE THREAD

**Issue by sarahliuict** [googleads/google-ads-dotnet#230]
Referenced the sample code to remove campaign/adgroup/ad, I wrote this code wanting to remove the userlist after CreateCustomerMatchUserList -

      UserListServiceClient userListService = _adsClient.GetService(Services.V4.UserListService);
      UserListOperation userListOperation = new UserListOperation { Remove = audienceResourceName };   
      try
      {
        MutateUserListsResponse response = userListService.MutateUserLists(customerId.ToString(), new UserListOperation[] { userListOperation });

        return response.Results.FirstOrDefault()?.ResourceName;
      }
      catch (GoogleAdsException e)
      {
      }

but got an exception -
{{ "errors": [ { "errorCode": { "userListError": "USER_LIST_MUTATE_NOT_SUPPORTED" }, "message": "Creating user list without setting type in oneof user_list field, or creating/updating read-only user list types is not allowed.", "trigger": { "stringValue": "" }, "location": { "fieldPathElements": [ { "fieldName": "operations", "index": "0" } ] } } ] }}

Appreciate if you could add a proper sample code to remove the UserList or remove the members from the UserList into the repository.

Thanks
Sarah

**Comment by AnashOommen** [comment]
Hi Sarah,

I'm fairly sure that your code is correct, and that the API just doesn't support what you are trying to do. To double-check, could you please turn on logging and capture a request log for me? Mail it over to googleadsapi-support@google.com and address the email to Attn:Anash so it gets routed to me.

Tx
Anash

**Comment by AnashOommen** [comment]
For any future reader, 

1) You cannot remove a userlist, you can only set its `membership_status` to `CLOSED`. https://developers.google.com/google-ads/api/reference/rpc/v8/UserList#membership_status.

2) There may be some userlist types that don't support closing. Check the `read_only` field first. https://developers.google.com/google-ads/api/reference/rpc/latest/UserList#read_only
