### ISSUE TITLE
Include/Exclude hotel group(s) in/from Hotel Campaigns 

### ISSUE THREAD

**Issue by ricardohns** [googleads/google-ads-dotnet#240]
**Problem description:** We are currently adding **Hotel Groups** to our **Ad Group** via Google Ads platform.
This is achieved by following those steps:

1. Select **All campaigns**.
2. Choose a campaign (let's say CPC - fixed per night).
3. Click on an **Ad Group** for the chosen campaign.
4. In the second side nav bar click on **Hotel Groups**
5. Select one item (hotel) from the grid and include/exclude it in/from the hotel groups.

Note.: There is also a list of **Ungrouped (from Hotel Ads Center)** that is basically all hotels available (if I am not mistaken).

I have already read the documentation and tried to follow the guided steps, yet I could not follow through from step 4.
The 6 steps I tried to follow is on the bttn of this page: https://developers.google.com/google-ads/api/docs/hotel-ads/overview

**Expected solution:** In your documentation and also in the solution examples, there are various examples on how to create Campaign, Ad Group, Ad Group Ad all programmatically.

I would would like an example on how to ad a hotel to Campaign -> Ad Group -> Hotel Group as per my steps above, I need to do this in code, implementing this in my API, is it possible?

Thanks

**Comment by AnashOommen** [comment]
I've added a code example on https://github.com/googleads/google-ads-dotnet/pull/242/files. Please feel free to use it.

**Comment by AnashOommen** [comment]
Closing this bug, since this is now part of the release distibution.
