### ISSUE TITLE
Google Ads API - Error received from peer ipv6

### ISSUE THREAD

**Issue by mbinder007** [googleads/google-ads-dotnet#243]
Hi, I am trying to make an update call to GoogleAds and I received the message below. Please could someone help?

Michael

Method Name: /google.ads.googleads.v5.services.CampaignService/MutateCampaigns
Host: https://googleads.googleapis.com

Headers: {
  "x-goog-api-client": "gl-dotnet/3.0.0 gapic/5.0.0 
gax/3.1.0+acac8dfe75024cb815497966fe13fc6cb1a1b0ed grpc/2.31.0",
  "developer-token": "REDACTED",
  "login-customer-id": "xxx-xxx-xxxx",
  "x-goog-request-params": "customer_id=xxxxxxxxxx"
}

{ "customerId": "xxxxxxxxxx", "operations": [ { "update": { "resourceName": 
"customers/xxxxxxxxxx/campaigns/xxxxxxxxxxx", "status": "PAUSED", "networkSettings": { 
"targetSearchNetwork": false } }, "updateMask": 
"resourceName,status,networkSettings.targetSearchNetwork" } ] }

-- Response
--------
Headers: {
  "date": "Thu, 01 Oct 2020 11:01:47 GMT",
  "alt-svc": "h3-Q050=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3- 
   T051=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3- 
Q043=\":443\"; 
ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
}

Fault: Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Internal error encountered.", 
DebugException="Grpc.Core.Internal.CoreErrorDetailException: 
{"created":"@1601550107.849000000","description":"Error received from peer ipv6: [2a00:1450:4009:819::200a]:443","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1062,"grpc_message":"Internal error encountered.","grpc_status":13}")
----------------END API CALL----------------

**Comment by AnashOommen** [comment]
Hi @mbinder007, does this issue persist?
