### ISSUE TITLE
Google Ads API - saving reports as XML/JSON dynamically

### ISSUE THREAD

**Issue by AlesSturala** [googleads/google-ads-dotnet#244]
Hello,
in our .NET project we're in the process of migrating to the new Google Ads API from the Google AdWords API. In the old version what we do is running lot of AWQL queries and storing those into AVRO file for big data analysis (AVRO is similar format to CSV or JSON). Basically we would parse the received XML report and transform it into AVRO, all on the meta-level - so each node of the XML one by one into appropriate field with the proper data type.

**Problem:**
With the new API, all data from the GoogleAdsService is received not as XML, but as DTO/parsed objects. Basically I didn't find any way how to save received data dynamically into CSV/XML/JSON/AVRO.

**Question:** Can you help me how to get to a level higher data (I guess data are sent as JSON?) so I can process the data the way we need, prepare it for big data analysis, store it on a disk and all those use-cases that were possible in the old Google AdWords API?

Thank you in advance.

**Comment by AnashOommen** [comment]
Apologies for the delay. The data is sent back and forth as serialized protobuf objects, but converting back and forth into JSON is relatively easy. Does this work for you?

```c#
string rowJson = JsonFormatter.Default.Format(googleAdsRow);
GoogleAdsRow parsedRow = GoogleAdsRow.Parser.ParseJson(rowJson);
```

**Comment by AnashOommen** [comment]
Hi @AlesSturala, I'm closing this issue for now, feel free to reopen if you continue to face issues and the suggested workaround doesn't work for you.
