### ISSUE TITLE
Bidding strategy update does not apply when mutating campaign

### ISSUE THREAD

**Issue by almamouz** [googleads/google-ads-dotnet#255]
- Client library version 6.0.0

- .NET Core 3.1

- Windows

**Actions taken**
Mutate a campaign assigning it a bidding strategy.

```
var campaignToUpdate = new GoogleAdsResources.Campaign
{
	ResourceName = ResourceNames.Campaign(request.UserRequest.ClientCustomerId, request.Campaign.Id)
};

if (requestedCampaign.StandardBiddingStrategy != null)
{
	switch (biddingStrategyType)
	{
                { ... }
		case BiddingStrategyType.ManualCpc:
			campaignToUpdate.ManualCpc = new ManualCpc();
			if (requestedCampaign.StandardBiddingStrategy.EnhancedCpcEnabled.HasValue)
			{
				targetCampaign.ManualCpc.EnhancedCpcEnabled =
					requestedCampaign.StandardBiddingStrategy.EnhancedCpcEnabled.Value;
			}
			break;
		case BiddingStrategyType.ManualCpm:
			campaignToUpdate.ManualCpm = new ManualCpm();
			break;
		case BiddingStrategyType.ManualCpv:
			campaignToUpdate.ManualCpv = new ManualCpv();
			break;
		case BiddingStrategyType.MaximizeConversions:
			campaignToUpdate.MaximizeConversions = new MaximizeConversions();
			break;
		case BiddingStrategyType.TargetCpa:
			campaignToUpdate.TargetCpa = new TargetCpa();
			if (requestedCampaign.StandardBiddingStrategy.Common.TargetCpa.HasValue)
			{
				campaignToUpdate.TargetCpa.TargetCpaMicros =
					requestedCampaign.StandardBiddingStrategy.Common.TargetCpa.Value;
			}
			break;
	}
}

var campaignOperation = new CampaignOperation
{
	Update = campaignToUpdate,
	UpdateMask = FieldMasks.AllSetFieldsOf(campaignToUpdate) // fields mask gets updated properly
};
```

**Expected result**
Campaign has the newly assigned bidding strategy

**Actual result**
Mutation succeeds but campaign still has the old bidding strategy. No change is logged in change history.

Mutation with bidding strategies that have additional properties works fine though. This issue is for bidding strategies without extra properties such as ManualCpm, ManualCpv and MaximizeConversions. The field mask seems to pick the change though: `{"resourceName":"...", "maximizeConversions": { } }`
 
There are a couple of related posts in the group, but one of them redirects the issue to the java lib, so I thought of posting this here instead.
- https://groups.google.com/g/adwords-api/c/GB4sReLzky4/m/Lw85VbDeAAAJ
- https://groups.google.com/u/3/g/adwords-api/c/6AyogtFnN1c

**Comment by AnashOommen** [comment]
@almamouz This seems more an issue with the API itself rather than the client library, but I'll keep this open for now just to make sure that the server issue isn't masking another client library issue.

**Comment by AnashOommen** [comment]
@almamouz Was this issue fixed for you? Did you get a resolution from the forum threads?

**Comment by almamouz** [comment]
@AnashOommen Not yet. There haven't been any updates in the forum either

**Comment by AnashOommen** [comment]
Hi @almamouz 

Could you give it another try? I looked up the internal issue, and it seems to be fixed. So something like this would work:


maximize_conversions

**Comment by almamouz** [comment]
Works fine now, I didn't have to change anything. Thanks!
