### ISSUE TITLE
How to handle refresh tokens outside GoogleAdsConfig

### ISSUE THREAD

**Issue by AdrianPell** [googleads/google-ads-dotnet#262]
**Describe the problem you are trying to solve**

This is a (belated) followup to #118 (@AnashOommen).

I am trying to figure out how to properly handle refreshing access tokens outside the library (we store access and refresh tokens in our own store). We can ensure that we have a refreshed access token before calling methods on a GoogleAdsClient using the overload of CreateCredentials() on GoogleAdsConfig. However, it seems that deep in the infrastructure, CachedChannelFactory has a static cache of all credentials (at least until the channel is marked as shut down).

The difficulty that creates is that CreateCredentials() on our overloaded GoogleAdsConfig is only called once .. and after an hour, the resulting access is no longer valid, resulting in an Unauthenticated error from the provider.

**Describe the solution you would like**

Ideally, there should be some way to either defeat the cache or request that credentials expires after a certain period.

**Describe alternatives you've considered**

For now, I have resorted to trying to defect the cache by changing its key. I'm currently using the OAuth2PrnEmail field (which is unused in an APPLICATION mode) to contain some token (I'm actually using the Access Token for now).

The downside to that is that the credential cache will probably grow without bound, which is undesirable in a heavily used system.

The other difficulty is that our token store is provided to the caller of GoogleAdsClient by dependency injection (on a per-request basis) and therefore is unavailable when/if GetAccessTokenForRequestAsync() on the *original* ICredential is called by the infrastructure prior to a request.

**Comment by AnashOommen** [comment]
Hi Adrian, 

I release v7.1.0 which has a setting named `UseChannelCache` that allows you bypass the channel cache. Set

```
config.UseChannelCache = false;
```

when overriding the `CreateCredentials()` method.

Let me know if this addresses your issue.
