### ISSUE TITLE
appsettings.json OAuth service account example 

### ISSUE THREAD

**Issue by andreylima** [googleads/google-ads-dotnet#267]
I'm trying to run "UploadClickConversionsRequest", but I'm working with .Net Core 3.1 that doesn't use the app.config, but the **appsetting.json instead.** I can't find any documentation about it.

Does someone have an example of authentication in this case using a service account?

When I try to send the conversion I get this error:
RpcException: Status(StatusCode="Unavailable", Detail="Getting metadata from plugin failed with error: Exception occurred in metadata credentials plugin. Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token",

Thanks
Andrey Lima

**Comment by AnashOommen** [comment]
Hi Andrey,

Take a look at https://developers.google.com/google-ads/api/docs/client-libs/dotnet/configuration, it has some examples.

**Comment by andreylima** [comment]
Hi Anash, thanks for the link, I realized how can I authenticate from the data in appsettings.json, altough I have to get the refresh token first.

For that, I'm using the Desktop Application Authenticate example, but I'm not sure if it is the right one for Service Account:
https://github.com/googleads/google-ads-dotnet/blob/06c62237162a8e2e16f61e1d8ba03a836728f230/examples/Authentication/AuthenticateInDesktopApplication/Program.cs

The message I get when I try to authenticate is: 
The redirect URI in the request, http://127.0.0.1:63453/authorize/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}


But when I try to add the url in the authorized redirect URI's, it can't accept Local urls. Any solution for this?

**Comment by AnashOommen** [comment]
For service account, 

1) Follow this guide to enable domain-wide delegation and impersonation at your GSuite domain. https://developers.google.com/google-ads/api/docs/oauth/service-accounts#setting_up_service_account_access

2) Then set up the configuration parameters in your appsettings.json: https://developers.google.com/google-ads/api/docs/client-libs/dotnet/oauth-service#step_2_-_setting_up_the_client_library_using_json_configuration_file

Google Ads doesn't support service accounts without account impersonation (i.e. you cannot invite a robot account to manage a Google Ads account).

**Comment by AnashOommen** [comment]
Or perhaps, a more correct thing to ask is, "why are you specifically looking for a service account flow"? Understanding your use case would help me guide you better.

**Comment by andreylima** [comment]
I'm looking for a service account because I want to send a conversion event to my google Ads Account every time an user is registered, and this happens on backend.

Basically, the application stucks at this point, with that refresh token error message:

                UploadClickConversionsResponse response =
                    conversionUploadService.UploadClickConversions(
                        new UploadClickConversionsRequest()
                        {
                            CustomerId = customerId.ToString(),
                            Conversions = { clickConversion },
                            PartialFailure = true,
                            ValidateOnly = false
                        });

Every flow I see let me to the desktop authentication, that I don't know if works, and I will try it right now.
I guess I was trying to insert the "authorized redirect URI" at the wrong place.

Do you think this is the right way, using "GoogleWebAuthorizationBroker.AuthorizeAsync"?

**Comment by AnashOommen** [comment]
For that workflow,

1) Create an OAuth client ID of type "desktop app".
2) Run the AuthenticateInDesktopApplication app and generate the credentials using the login for the account to which the conversions have to be imported (or Manager account, if you have more than one account).
3) Then make calls using this credential. Just make sure you set the customerId to the correct account to which the conversions should be imported.

**Comment by andreylima** [comment]
Anash, sorry to bother again.

I've tried these ways:

1 - Create an OAuth client ID of type "desktop app".
Used this function trying to authenticate:
`
            Task<UserCredential> task = GoogleWebAuthorizationBroker.AuthorizeAsync(
                 secrets,
                 new string[] { GOOGLE_ADS_API_SCOPE },
                 String.Empty,
                 CancellationToken.None,
                 new NullDataStore()
             );
`
The result is a new google login window, but this is not what I want, I want to Authorize it from the backend, that's why I think I should use the service account authentication, that takes me to the next step:

2 - Created a Service account with G Suite Domain-wide Delegation enabled, that automatically created a Client of type "service account type".
Following the instructions of the link you gave me, I have to set up the configuration in the app.config. But, as I told before, my .net version doesn't use the app.config, but appsettings.json instead.
I found this other documentation teaching how to configure using a settings.json file:
https://developers.google.com/google-ads/api/docs/client-libs/dotnet/configuration , then I added the config information in the appsettings like this:
`
  "GoogleAdsApi": {
    "OAuth2Mode": "SERVICE_ACCOUNT",
    "OAuth2SecretsJsonPath": "{real path}",
    "OAuth2PrnEmail": "{real e-mail}"
  }
`
 And then I instatiated it at startup.cs like this:
`
IConfigurationSection section = Configuration.GetSection("GoogleAdsApi");
GoogleAdsConfig config = new GoogleAdsConfig(section);
GoogleAdsClient client = new GoogleAdsClient(config);
`

With this, I can't get the refreshToken on the return, and still got the same first error of:
"Missing required parameter: refresh_token",

Should this instatiation return the refresh token? Am I missing something?

Thanks again

**Comment by AnashOommen** [comment]
1) Sounds good.
2) This seems very familiar, there was a recent issue where the library wasn't reading `OAuth2Mode` setting and thus complaining about a missing `refresh_token`. Try updating to the latest version of the library and see if the issue persists.

**Comment by AnashOommen** [comment]
@andreylima I am closing this issue for now, feel free to reopen if the issue persists.
