### ISSUE TITLE
Search Stream Retry Recommendation

### ISSUE THREAD

**Issue by aukevin** [googleads/google-ads-dotnet#269]
While using `SearchStream`, I have occasionally run into exceptions that lead me to retry such as:
`Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Internal error encountered." ..)`
`Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded" ..)`
`Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="GOAWAY received" ..)`
`Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Stream removed" ..)`

There is a `RetrySettings` in the `CallSettings` that can be passed in with the `SearchStream` request, but it is not supported.

To work around this, I was testing the following code:

```
for (var count = 0; count < _retryMaxCount; count++)
{
    try
    {
        var results = new List<GoogleAdsRow>();
        _serviceClient.SearchStream(customerId, selectQuery, delegate (SearchGoogleAdsStreamResponse response)
        {
            results.AddRange(response.Results);
        });
        return results;
    }
    catch (Exception e)
    {
        Console.WriteLine(($"Caught exception: {e}");

        if (!IsRetryException(e))
        {
            Console.WriteLine($"Re-throwing non-retry exception.");
            throw;
        }
    }

    Thread.Sleep(delay);
    delay = delay.Add(_incrementInterval);
}
```

The issue is that this code appears to be flaky - sometimes it retries successfully and sometimes after the `Thread.Sleep`, there is no new request issued in the logs.

Is there a better way to add retries, or a specific amount of time I need to sleep before issuing a new request?

Thanks,
Kevin

**Comment by AnashOommen** [comment]
Some of these errors (goaway. stream removed) are actually the underlying connection breaking due to various reasons. So you need to obtain a different serviceclient instance.

Unfortunately grpc (the underlying transport protocol) itself doesn't support for server streaming requests, so there isn't anything we can do with the library's retry mechanism itself. We are aware of this limitation.

I'll check if there's a way to reuse the retry classes, so you can avoid these loops.

**Comment by aukevin** [comment]
Thanks for the info! I'll edit the code to regenerate the `ServiceClient` instance and see how it goes.

I'll also look forward to any improvements from this library -
It seems like the kind of thing many people might want to be readily available in order to reduce manual retries.

**Comment by mahwishs** [comment]
I am having to write my own retry as well. But what am noticing is something odd with the SearchStream method it self. 

It just hangs. No errors. Then roughly an hour later responds. Is there a setting to reduce the amount of wait time between no result.
 
this was one instants of the stream just hanging after RequestID: fTywBYOrcxVko-PJSMO5Lg

 GoogleAds.SummaryRequestLogs Information: 1 : [2021-03-05 01:25:23Z] - Request made: Host: https://googleads.googleapis.com, Method: /google.ads.googleads.v6.services.GoogleAdsService/SearchStream, ClientCustomerID: [redacted],  RequestID: fTywBYOrcxVko-PJSMO5Lg, IsFault: False, FaultMessage: 
GoogleAds.SummaryRequestLogs Warning: 1 : [2021-03-05 02:25:23Z] - Request made: Host: https://googleads.googleapis.com, Method: /google.ads.googleads.v6.services.GoogleAdsService/SearchStream, ClientCustomerID: [redacted],  RequestID: , IsFault: True, FaultMessage: Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1614911123.689000000","description":"Error received from peer ipv4:172.217.4.106:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}")

Here is how I am making the requests.
`
  var _googleAdsServiceClient = googleAdsClient.GetService(Services.V6.GoogleAdsService);
  var query = $@"SELECT
                                    campaign.id,
                                    campaign.advertising_channel_type,
                                    campaign.name,
                                    campaign.status,
                                    campaign.start_date,
                                    campaign.end_date,
                                    campaign_budget.amount_micros,
                                    metrics.clicks,
                                    metrics.impressions,
                                    metrics.cost_micros,
                                    metrics.all_conversions,
                                    metrics.conversions,
                                    segments.date,
                                    segments.device,
                                    segments.ad_network_type
                            FROM campaign
                            WHERE campaign.advertising_channel_type IN ('UNKNOWN','DISPLAY','SEARCH','SHOPPING','VIDEO')
 AND segments.date <= '2020-02-01' AND segments.date <= '2020-02-02'";

       
var retrySettings = RetrySettings.FromExponentialBackoff(
                            maxAttempts: _maximumRetryAttempts,
                            initialBackoff: _initialBackOffInSeconds,
                            maxBackoff: _maxBackoffInSeconds,
                            backoffMultiplier: 2.0,
                            retryFilter: RetrySettings.FilterForStatusCodes(StatusCode.DeadlineExceeded, StatusCode.Internal, StatusCode.Unavailable, StatusCode.Unknown));
                        var callSettings = CallSettings.FromRetry(retrySettings)
                                .WithTimeout(TimeSpan.FromMinutes(10))
                                .WithDeadline(DateTime.UtcNow.AddMinutes(10));

                        Action<GoogleAdsServiceClient, string, ConcurrentStack<GoogleCampaignModel>> callGoogleSearchApi = (googleAdsServiceClient, customerId, campaigns) =>
                        {
                            googleAdsServiceClient.SearchStream(
                                customerId: customerId,
                                query: query,
                                callSettings: callSettings,
                                responseCallback: (SearchGoogleAdsStreamResponse streamResponse) =>
                                {
                                    var results = streamResponse.Results;
                                    if (results.Any())
                                    {
                                        campaigns.PushRange(streamResponse.Results.Select(googleAdsRow => GoogleAdsManagerExtensions.PopulateGoogleCampaignModel(googleAdsRow)).ToArray());
                                    }
                                });
                        };

                        await GoogleAdsManagerExtensions.DownloadReportWithRetryAsync(
                            googleAdsServiceClient: _googleAdsServiceClient,
                            callSettings: callSettings,
                            customerId: customerId.ToString(CultureInfo.InvariantCulture),
                            callGoogleEndpoint: callGoogleSearchApi,
                            googleEndpointResponse: campaigns,
                            logger: Logger).ConfigureAwait(false);


 public static async Task<bool> DownloadReportWithRetryAsync(GoogleAdsServiceClient googleAdsServiceClient, CallSettings callSettings, string customerId, Action<GoogleAdsServiceClient, string, ConcurrentStack<GoogleCampaignModel>> callGoogleEndpoint, ConcurrentStack<GoogleCampaignModel> googleEndpointResponse, ILogger logger)
        {
            EnsureArg.IsNotNull(callGoogleEndpoint, nameof(callGoogleEndpoint));
            EnsureArg.IsNotNull(callSettings, nameof(callSettings));

            var isComplete = false;
            int retryCount = 0;
            while (!isComplete)
            {
                try
                {
                    callGoogleEndpoint(googleAdsServiceClient, customerId, googleEndpointResponse);
                    isComplete = true;
                }
                catch (Exception ex)
                {
                    retryCount++;

                    GoogleAdsException gae = null;
                    if (ex is AggregateException)
                    {
                        gae = GoogleAdsException.FromTaskException((AggregateException)ex);
                    }

                    if (ex is GoogleAdsException)
                    {
                        gae = (GoogleAdsException)ex;
                    }

                    if (gae == null || gae.StatusCode == StatusCode.ResourceExhausted || retryCount > callSettings.Retry.MaxAttempts)
                    {
                        logger.LogCritical(ex, $"{nameof(DownloadReportWithRetryAsync)}: An error occurred for customer id: {customerId} while getting campaigns.");

                        // If we throw ex, we are getting null value for Grpc.Core.Metadata. This value is not provided by Google.
                        // So we are throwing new exception with ex.message.
                        throw new Exception(ex.Message);
                    }
                    else if (callSettings.Retry.RetryFilter(ex))
                    {
                        isComplete = false;
                        var retryInSeconds = callSettings.Retry.InitialBackoff * retryCount;
                        logger.LogInformation(gae, $"{nameof(DownloadReportWithRetryAsync)}: An Error occurred Customer Id: {customerId} while getting campaigns. Retry attempt {retryCount} in {retryInSeconds} seconds.");
                        await Task.Delay(retryInSeconds).ConfigureAwait(false);
                    }
                }
            }

            return isComplete;
        }
`

**Comment by AnashOommen** [comment]
There is a timeout setting in the AppConfig. The default is set to 60
minutes, but you can set it to something smaller that's appropriate for
your API call.

**Comment by mahwishs** [comment]
So what you are saying is that I need to resolve the client => new GoogleAdsClient(googleAdsConfig) per request

I am currently reusing the same client for all the requests until I fetched for all the customer Ids. 

So my call to the Api looks like this now.
`
                        Action<GoogleAdsServiceClient, string, ConcurrentStack<GoogleCampaignModel>> callGoogleSearchApi = (googleAdsServiceClient, customerId, campaigns) =>
                        {
                            var googleAdsClient = _googleAdsConfiguration.GetGoogleAdsClient();
                            googleAdsClient.Config.Timeout = 120000;
                            var googleAdsServiceClient1 = googleAdsClient.GetService(Services.V6.GoogleAdsService);

                            var results = googleAdsServiceClient1.Search(
                                customerId: customerId,
                                query: query);

                            if (results.Any())
                            {
                                campaigns.PushRange(results.Select(googleAdsRow => googleAdsRow).ToArray());
                            }
                        };`

**Comment by AnashOommen** [comment]
There's a simpler way to set the timeout: You can pass a `CallSettings` as one of the arguments to the method call itself. That callsetting override works only for the specific method call. Here's an example (other services are similar).

```c#
// Set a timeout of 10ms. This is useful for debugging purposes, since you should get a DeadlineExceededError immediately.
CallSettings callSettings = CallSettings.FromExpiration(
      Expiration.FromTimeout(new TimeSpan(0, 0, 0, 0, 10)));
long campaignId = 1234567890;
var campaign = new Campaign()
{
    ResourceName = ResourceNames.Campaign(customerId, campaignId),
    Status = CampaignStatus.Paused
};

CampaignOperation operation = new CampaignOperation()
{
    Update = campaign,
    UpdateMask = FieldMasks.AllSetFieldsOf(campaign)
};
// Get the CampaignServiceClient.
CampaignServiceClient campaignService = client.GetService(
    Services.V6.CampaignService);

 var result = campaignService.MutateCampaigns(new MutateCampaignsRequest()
 {
     CustomerId = customerId.ToString(),
     Operations = { operation },
     ResponseContentType = ResponseContentType.MutableResource
}, callSettings);
```
