### ISSUE TITLE
GoogleAdsConfig implementation is too tied to ConfigurationManager

### ISSUE THREAD

**Issue by VitalyDukhota** [googleads/google-ads-dotnet#27]
Current GoogleAdsConfig implementation is tied to ConfigurationManager, which is only used by .NET Framework for desktop programs. .NET Web applications, and specifically .NET Core applications use WebConfigurationManager which the current implementation of GoogleAdsConfig ignores, and so it doesn't pick up configuration from it. It's not a big deal because there is LoadConfigRoot(IConfigurationRoot configurationRoot) mentioned above, which allows loading configuration from anywhere - but it requires a bit of custom coding. Perhaps having a public constructor which takes a Dictionary or similar would be nice for cases when IConfiguration is not available.

**Comment by AnashOommen** [comment]
Fixed in v0.7.1.
