### ISSUE TITLE
Can't remove bids

### ISSUE THREAD

**Issue by tinmek** [googleads/google-ads-dotnet#284]
**Which version of the client library are you using?**
8.0.0

**Which version of .NET are you using?**
.NET 5, .NET Standard 2.1

**Which operating system (Linux, Windows, ...) and version?**
Windows 10

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
adGroup.TargetCpaMicros = 0;
adGroup.CpcBidMicros = 0;

**Expected result**
Reference this https://developers.google.com/google-ads/api/docs/campaigns/bidding/set-bids#removing_bids
Those property should accept null value. They could also accept 0 like Adwords API which also allow removing bids with this.

**Actual result**
API call return error "Too low" when set value to 0 and they don't accept null like documented.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by AnashOommen** [comment]
No, the API doesn't work like that, and hence we don't plan to fix this in the client library either. I'll file an issue to get the documentation fixed.

Code like this should clear a bid field.

```c#
AdGroup adGroup = new AdGroup()
{
    ResourceName = ResourceNames.AdGroup(customerId, adGroupId)
};

FieldMask fieldMasks = FieldMasks.AllSetFieldsOf(adGroup);
FieldDescriptor field = AdGroup.Descriptor.Fields[AdGroup.CpcBidMicrosFieldNumber];
fieldMasks.Paths.Add(field.Name);

MutateAdGroupsRequest request = new MutateAdGroupsRequest()
{
    CustomerId = customerId.ToString(),
    Operations =
    {
        new AdGroupOperation()
        {
            Update = adGroup,
            UpdateMask = fieldMasks
        }
    }
};

AdGroupServiceClient adGroupService = client.GetService(
    Services.V7.AdGroupService);
MutateAdGroupsResponse response = adGroupService.MutateAdGroups(request);
```

**Comment by tinmek** [comment]
@AnashOommen The suggested code doesn't work.
When using AdGroupServiceClient it still returns BID_TOO_SMALL as same as setting the field value to 0.
When using BatchJobServiceClient it returns "The required field was not present., mutate_operations[0].ad_group_operation.update.cpc_bid_micros" error instead.
