### ISSUE TITLE
GetAdGroups and GetCampaigns Examples Not Working?

### ISSUE THREAD

**Issue by YodasMyDad** [googleads/google-ads-dotnet#29]
I have just tried GetAdGroups and GetCampaigns examples. Neither of which work. I have the correct credentials, customer id and campaign or adgroup id.

The searchPagedResponse returns nothing for each. Can you please test @AnashOommen ... Really appreciate the examples you have done, but it's very frustrating when you spend a day setting up the project in .Net Core and then find the examples don't actually work. 

I am setting up the config manually if that makes any difference? It shouldn't as some examples do work.

          var adsConfig = new GoogleAdsConfig()
            {
                DeveloperToken = googleAdsApiSettings.DeveloperToken,
                OAuth2Mode = googleAdsApiSettings.OAuth2Mode,
                OAuth2ClientId = googleAdsApiSettings.OAuth2ClientId,
                OAuth2ClientSecret = googleAdsApiSettings.OAuth2ClientSecret,
                OAuth2RefreshToken = googleAdsApiSettings.OAuth2RefreshToken
            };

**Comment by AnashOommen** [comment]
Hi,

Could you please turn on logging, run these examples and send me the logs at adwordsapi-support@google.com? This is the mail alias for the official product support queue, and you can reach me by adding Attn: Anash Oommen in your mail.

Tx
Anash
