### ISSUE TITLE
Can't update campaign bid strategy 

### ISSUE THREAD

**Issue by STNarek** [googleads/google-ads-dotnet#294]
Client Version: **6.00**

.NET version: **.NET 3.1**

Platform: **MacOS**

**Actions taken**
I am trying to set campaign bidding strategy to maximize conversion value. 
Here's the code: 
```
            var updatedCampaign = new Campaign {
                ResourceName = campaignResourceName,
                MaximizeConversionValue = new MaximizeConversionValue {}
            };

            var operation = new CampaignOperation {
                Update = updatedCampaign,
                UpdateMask = FieldMasks.AllSetFieldsOf(updatedCampaign) 
            };

            await campaignServiceClient.MutateCampaignsAsync(accountId, new []{operation});
```

**Expected result**
The campaign bidding strategy should be set to maximize conversion value.

**Actual result**
The mutate request silently succeeds but nothing changes on the campaign. The field mask won't pickup the change at all. The same is true for all other union fields. 

Building the field mask manually does not help either, as the API won't allow to set the union field 
directly. It allows only setting subfields, which are in this case optional.

**Comment by AnashOommen** [comment]
Hi @STNarek, could you try adding the following line as a temporary workaround?

`fieldMasks.Paths.Add("maximize_conversion_value");`

Let me know if that fixes the issue.

**Comment by STNarek** [comment]
Hi @AnashOommen. Thanks for the suggestion. I just tried it and got the following error: 
```
{
  "StatusCode": 3,
  "Details": "Request contains an invalid argument.",
  "RequestId": "kTl3jz_tt2ibFSTS0Q2cew",
  "Failure": {
    "errors": [
      {
        "errorCode": {
          "fieldMaskError": "FIELD_HAS_SUBFIELDS"
        },
        "message": "The field mask updated a field with subfields: 'maximize_conversion_value'.",
        "location": {
          "fieldPathElements": [
            {
              "fieldName": "operations",
              "index": 0
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by AnashOommen** [comment]
@STNarek Try setting the fieldmask as `maximize_conversion_value.target_roas` and do not specify the `target_roas` field, like this:

```c#
var updatedCampaign = new Campaign {
    ResourceName = campaignResourceName,
    MaximizeConversionValue = new MaximizeConversionValue {}
};

var fieldMask = FieldMasks.AllSetFieldsOf(updatedCampaign);
fieldMasks.Paths.Add("maximize_conversion_value.target_roas");

var operation = new CampaignOperation {
    Update = updatedCampaign,
    UpdateMask = FieldMasks.AllSetFieldsOf(updatedCampaign) 
};
```

**Comment by AnashOommen** [comment]
Pls reopen if the issue persists.

**Comment by smaralbashi** [comment]
@AnashOommen We have the same issue while setting MaximizeConversions or MaximizeConversionsValue on the campaigns using Google.Ads.GoogleAds version 10.2.0 and V9 of client library. 

We are using this code : 
 var additionalPaths = new List<string>();
                switch (cs.BiddingStrategyTypeToEnforce)
                {
                    case BiddingStrategyToEnforce.MaximizeConversions:
                        campaignEntity.MaximizeConversions = new MaximizeConversions();
                        additionalPaths = new List<string> { "maximize_conversions.target_cpa" };
                        break;
                    case BiddingStrategyToEnforce.MaximizeConversionsValue:
                        campaignEntity.MaximizeConversionValue = new MaximizeConversionValue { };
                        additionalPaths = new List<string> { "maximize_conversion_value.target_roas" };
                        break;
                }
                
                var operation = new CampaignOperation
                {
                    Update = campaignEntity,
                    UpdateMask = FieldMasks.AllSetFieldsOf(campaignEntity)
                };

                operation.UpdateMask.Paths.AddRange(additionalPaths);
