### ISSUE TITLE
"Failed to deserialize response message" error on report fetch

### ISSUE THREAD

**Issue by metkor** [googleads/google-ads-dotnet#306]
I am fetching searchterm_view report for some customer ids. It is working for some customers but for some customer ids. I am getting this error:

Type = Grpc.Core.RpcExceptionMessage = Status(StatusCode="Internal", Detail="Failed to deserialize response message.")
Source = System.Private.CoreLibStatus = Status(StatusCode="Internal", Detail="Failed to deserialize response message.")StatusCode = Internal

I set environment variables for grpc logs. But there is nothing meaningful. Error message also tells nothing.

Is it a known issue or could you provide me some documentation to solve this problem? Because I could not find.

Thanks

**Comment by AnashOommen** [comment]
That's strange... I have quite a bit of followup questions...

1) if you enable logging as per https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging, does it give anything in the detailed logs?
2) Any chance you can capture a request ID for a failed request? 
3) Does the problem go away if you pick the latest client library?
4) Is this replicable?

I suspect something is coming back from the server that the client library stubs don't know about (and hence deserializing fails). The question is how to find what it is.

**Comment by metkor** [comment]
Hello @AnashOommen ,

I realized that this occurs when I used SearchStream with big accounts. On small accounts it is working. If I use Search with paging on big accounts it is working. So I go with search and paging. 

1) I will check again.
2) I had request id, I will try to get it again and I will share it.
3) It is not related with version.
4) Yes, please call searchstream on big accounts. 

Thanks

**Comment by AnashOommen** [comment]
Hi Mehmet,

Choosing Search instead of Searchstream for large accounts has performance
implications due to multiple server round-trips.

Can you find me an example log / request ID to replicate this error?

Tx
Anash

**Comment by metkor** [comment]
Hello again,

I am getting same error for both search and searchstream now. 

I have this request id in error message.

[Entry: key=request-id, value=HhcI24vseuHmzCWwwlJ15A]

Thanks
