### ISSUE TITLE
SERVICE_ACCOUNT set up in C#

### ISSUE THREAD

**Issue by EfimenkoAndrew** [googleads/google-ads-dotnet#318]
**What is your question?**

Hello, I am trying to setup SERVICE_ACCOUNT authorisation and I faced this issue

{
  "StatusCode": 16,
  "Details": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
  "RequestId": "<REPLASED WITH THIS TEXT>",
  "Failure": {
    "errors": [
      {
        "errorCode": {
          "authenticationError": "NOT_ADS_USER"
        },
        "message": "User in the cookie is not a valid Ads user."
      }
    ],
    "requested": "<REPLASED WITH THIS TEXT>"
  }
}
I enabled API in google console project. How to solve this issue?

**Comment by AnashOommen** [comment]
Google Ads API requires service account impersonation. The error is basically saying that the service account is not impersonating a user who is a valid user in the Google Ads account to which you are trying to make an API call.

See https://developers.google.com/google-ads/api/docs/oauth/service-accounts for details on how to use service accounts in Google Ads. Also, is there a reason why the refresh-token based flow won't work for you?
