### ISSUE TITLE
By using search stream I am getting the data of cost_per_conversion but can you tell in which format it is?  In the same way, average_cpc are also available but I do not know its format.  And what metrics do I need in campaign for cost and conversion rate ? I have attached screenshot

### ISSUE THREAD

**Issue by ysunil702** [googleads/google-ads-dotnet#323]
By using search stream I am getting the data of cost_per_conversion but can you tell in which format it is?

In the same way, average_cpc are also available but I do not know its format.
I want data in rupees format.
I have attached screenshot.

And what metrics do I need in campaign for cost and conversion rate ?

Thank you

![image](https://user-images.githubusercontent.com/49015306/138825865-576af640-5427-41a2-a96f-928224187661.png)

![image](https://user-images.githubusercontent.com/49015306/138825848-eabe2222-935a-446b-8669-8d855e2b583a.png)

**Comment by AnashOommen** [comment]
@ysunil702 Apologies for the delay. Money fields are generally retuned in micros, which is calculated as 1000000 micros = 1 currency unit of the account. So if this were INR, then 1 INR = 1M micros.

https://developers.google.com/adwords/api/docs/guides/reporting

https://developers.google.com/google-ads/api/fields/v9/overview_query_builder is a good place to construct your queries. For your specific question, I'm guessing you need a query like
```
select campaign.id, campaign.name, metrics.cost, metrics.conversions, metrics.cost_per_conversion from campaign where segments.date >= 2021-01-01 and segments.date <= 2021-01-31
```
