### ISSUE TITLE
Separate Summary and Detailed Log Message Generation

### ISSUE THREAD

**Issue by aukevin** [googleads/google-ads-dotnet#325]
Hi,

I noticed that a lot of resources were being used to compute long strings that were ultimately being discarded.
The culprit appears to be the `TraceUtilities.ShouldGenerateRequestLogs` method that checks whether either Summary or Detailed logs are required.
If either are required, both log message strings are computed, regardless of whether both are needed.

I thought it would be fun to fork the code and try my hand at separating the two logs types.
The PR for this attempt is here: https://github.com/googleads/google-ads-dotnet/pull/324

Could you take a look and let me know what you think?

Thanks,
Kevin

**Comment by AnashOommen** [comment]
Thanks Kevin for your contribution! I've accepted and merged the PR. Looking forward to more contributions!
