### ISSUE TITLE
Error in using Google Ads API i am getting error in .net library although I have updated all

### ISSUE THREAD

**Issue by vanijyabiz** [googleads/google-ads-dotnet#326]
" Error loading native library. Not found in any of the possible locations: D:\Shikhar\VanijyaV2\bin\grpc_csharp_ext.x86.dll,D:\Shikhar\VanijyaV2\bin\runtimes/win-x86/native\grpc_csharp_ext.x86.dll,D:\Shikhar\VanijyaV2\bin\../..\runtimes/win-x86/native\grpc_csharp_ext.x86.dll
  Source=Grpc.Core"

detailed error with stacktrace attached as a text file .. ( code screenshot also attached )

I have re-installed all Google ads client libraries and using .net version 4.7.2 

Also updated developer token, client id and client secret to web.config 

Please help us in solving this issue so that we can move forward.

**Comment by vanijyabiz** [comment]
Hi ,

I am waiting for response to my query

**Comment by AnashOommen** [comment]
@vanijyabiz could you try adding a dependency to Grpc.Core directly in your project? That should temporarily address this issue.

It would also be helpful to get a project example that can replicate the issue, plus the environment in which you are testing it. I'm familiar with the issue, but this is related to how Grpc works, and they would be the best team to investigate this issue further. I can loop in their team once I have a way to replicate this issue.

**Comment by vanijyabiz** [comment]
Sure I will try and get back if not resolved 
Thanks
