### ISSUE TITLE
AddCustomerMatchUserList

### ISSUE THREAD

**Issue by BrianM3** [googleads/google-ads-dotnet#327]
**Describe the bug:**

The class keeps timing out before the customer match list is created. Even if I change the following settings, it still never creates the list:
        private const int POLL_FREQUENCY_SECONDS = 30;
        private const int MAX_TOTAL_POLL_INTERVAL_SECONDS = 1600;

This is when running V8/AddCustomerMatchList.cs

**Steps to Reproduce:**
I have changed the following settings as well as increasing the numbers of users been created        
 private const int POLL_FREQUENCY_SECONDS = 30;
 private const int MAX_TOTAL_POLL_INTERVAL_SECONDS = 1600;

**Expected behavior:**
I am expecting the User Match list to be created

**Client library version and API version:**
I am using V8 of the examples downloaded from github.
The example been used is:

Client library version:V8
Google Ads API version:
.NET version:4.7.2
Installed: Google.Ads.Common V9.5.1, Google.Ads.GoogleAds V10.1.0, Google.Apis.Oauth2.v2 V1.55..0.1869
Operating system (Linux, Windows, ...) and version (if the bug is platform-specific): Windows 10

**Request/Response Logs:**
Log files have been uploaded to:
https://www.dropbox.com/sh/wiqv1gjzd4lq626/AACAEj6Z1v4JNP2yJ7McQpeYa?dl=0

**Anything else we should know about your project / environment**

Then on a side note. If I try to use the code with VB.NET. The following line will not run. This is due to the fact that **Operations** is a read only value. It seems to work in C#. But not in VB.NET. This is in class OfflineUserDataJobService.g.cs. But I think this should be corrected so that this class can be used within other languages too.

Dim request As AddOfflineUserDataJobOperationsRequest = New AddOfflineUserDataJobOperationsRequest() With {
                .ResourceName = offlineUserDataJobResourceName,
                .Operations = {BuildOfflineUserDataJobOperations()},
                .EnablePartialFailure = True}

**Comment by robonator7412** [comment]
from your log: Error:"invalid_request", Description:"Missing required parameter: refresh_token"
Seems like you didn't enter a refresh token in your client. Did you set your OAuth2RefreshToken in the GoogleAdsClient object?

**Comment by AnashOommen** [comment]
Hi,

Is this issue still present? if yes, could you reopen with a request ID attached? Logging instructions are available at https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging.
