### ISSUE TITLE
Error While Uploading Offline Conversion

### ISSUE THREAD

**Issue by logi-ppc** [googleads/google-ads-dotnet#336]
Hello,

I am trying to upload offline conversion to google ads using c#.net and [this nuget](https://www.nuget.org/packages/Google.Ads.GoogleAds/) and getting the below error. Can you please help me out to fix this issue?

![image](https://user-images.githubusercontent.com/96433930/146793836-60b17c6b-f107-4e27-8002-bdee9111d6a6.png)

As the error is saying Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential, Although the oAuth 2 access token is presented in the app.config of the application as you can see below:

![image](https://user-images.githubusercontent.com/96433930/146793944-8e3349a8-0353-4409-b611-45d058a20647.png)

Kindly let me know what I can do to fix the issue!

Thanks...

**Comment by AnashOommen** [comment]
Hi,

Do you still face this issue? If yes, pls reopen and attach a request ID. Logging instructions are at https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging
