### ISSUE TITLE
[Urgent] FinalUrls is READONLY

### ISSUE THREAD

**Issue by ullfindsmit** [googleads/google-ads-dotnet#337]
**Describe the bug:**
FinalURLs is now readonly so I removed the line and now I get an error when trying to create a new Ad.

In the latest library the FinalUrls property is READONLY
Assembly Google.Ads.GoogleAds, Version=10.2.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc

However, in the earlier version it was NOT readonly.
Assembly Google.Ads.GoogleAds, Version=10.1.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc

What is the new way to set the FinalURLs value?

**Steps to Reproduce:**
```

                    // Create the ad group ad object.
                    AdGroupAd adGroupAd = new AdGroupAd
                    {
                        AdGroup = oAdGroup,
                        // Optional: Set the status.
                        Status = AdGroupAdStatus.Paused,
                        Ad = new Ad
                        {
                            **FinalUrls = { oAdGroupAd.FinalUrls },**
                            ExpandedTextAd = new ExpandedTextAdInfo
                            {
                                Description = CSVParameterObj.Description,
                                Description2 = CSVParameterObj.Description2,
                                HeadlinePart1 = CSVParameterObj.HeadlinePart1,
                                HeadlinePart2 = CSVParameterObj.HeadlinePart2,
                                HeadlinePart3 = CSVParameterObj.HeadlinePart3,
                                Path1 = CSVParameterObj.Path1,
                                Path2 = CSVParameterObj.Path2
                            }
                        }
                    };

```
**Expected behavior:**
Backward compatibility or documentation on how to fix.

**Client library version and API version:**
Assembly Google.Ads.GoogleAds, Version=10.2.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc
.NET version: Latest
Operating system (Linux, Windows, ...) and version (if the bug is platform-specific): Windows 10

**Request/Response Logs:**
{
  "StatusCode": 3,
  "Details": "Request contains an invalid argument.",
  "RequestId": "--removed--",
  "Failure": {
    "errors": [
      {
        "errorCode": {
          "collectionSizeError": "TOO_FEW"
        },
        "message": "Too few.",
        "location": {
          "fieldPathElements": [
            {
              "fieldName": "operations",
              "index": 0
            },
            {
              "fieldName": "create"
            },
            {
              "fieldName": "ad"
            },
            {
              "fieldName": "final_urls"
            }
          ]
        }
      }
    ],
    "requestId": "--removed--"
  }
}

**Anything else we should know about your project / environment**

Not at the moment.

**Comment by jradcliff** [comment]
Hi,

Thanks for opening the issue here. The error you received looks to be due to there being _zero_ final URLs on the ad sent in the request. Does the ad you're copying from (`oAdGroupAd`) have a non-empty `FinalUrls` collection?

Thanks

**Comment by ullfindsmit** [comment]
Yes, the property FinalUrls collection is blank.
The reason it is blank is because the property FinalURLs used to be read/write in 10.1 and is readonly in 10.2
There is no documentation as to HOW to set the value in 10.2.

**Comment by rivdiv** [comment]
I am hitting this issue as well with setting the FinalURls property on the AdGroupCriterion object. It is read only in both versions 9 and 10.2 which I just upgraded to.
https://groups.google.com/g/adwords-api/c/gPS2ibFplVY

**Comment by vipulpatel007** [comment]
ullfindsmit is right.
In Version 10.1 its allow to set value of final URL Plz check this
![Ad Expandend TextAPI](https://user-images.githubusercontent.com/92007939/147192351-cf0a4d0c-d696-4864-b9bc-a396d346673b.png)

**Comment by ullfindsmit** [comment]
@AnashOommen thank you for staying on this issue.
The issue is that the FinalURLs property is ReadOnly in 10.2.0.0 and I am
not able to set its value as you suggested

FinalUrls = { oAdGroupAd.FinalUrls }

**Comment by ullfindsmit** [comment]
[image: image.png]

>

**Comment by AnashOommen** [comment]
@ullfindsmit can you please attach a minimal project that illustrates the issue? Or otherwise, confirm if you can compile the attached Compilation Issues.zip?

**Comment by ullfindsmit** [comment]
I was finally able to get it to work.
The solution was to not use the inline declaration but instead to create a
new Ad object
Then instead of assigning the final urls, simply using
oAd.FinalURLs.Add("string")
