### ISSUE TITLE
V9 - Call View - Phone Number

### ISSUE THREAD

**Issue by Nemisys** [googleads/google-ads-dotnet#339]
I'm trying to retrieve all call records.  I've been able to pull all other call details from "call_view", but I do not see the actual phone number in the response. (nor accounted for in this library)

I'm able to pull this data via the reporting dashboard on the website via "Call Details", but i can't find this data anywhere in the API.  I've been on a hunt for this for a couple weeks now and figured this was my last option.

Appreciate any help!

**Comment by AnashOommen** [comment]
Hi,

Since this an API FR, could you kindly repost on https://groups.google.com/g/adwords-api?pli=1?
