### ISSUE TITLE
Does this library support .net core 5.0

### ISSUE THREAD

**Issue by ritesh-pangea** [googleads/google-ads-dotnet#340]
Hi I wanted to ask if this library supports .net 5.0. Based on this [documentation](https://github.com/googleads/google-ads-dotnet#supported-frameworks) I see it only supports .net core 3.0

However when I go to Google.Ads.GoogleAds in Nuget package Manager, I see .net5.0. Attached is the screenshot. 
![Screenshot Google Ads_Nuget_Package_Manager](https://user-images.githubusercontent.com/68885694/150024925-6fd683b6-477d-46aa-b575-3d9d0e403ac3.PNG)

**Comment by ritesh-pangea** [comment]
@AnashOommen

**Comment by AnashOommen** [comment]
I'll update the README.md, .net core 5.0 is fully supported.

**Comment by ritesh-pangea** [comment]
Thanks @AnashOommen

**Comment by anjanasagathiya** [comment]
@AnashOommen Can you tell me What is Conversion Action Id in Conversion Action Because I couldn't find any ConversionActionId in Conversiondetail from Google Ads Manager Account there is shows only Conversion Name in Google Ads Manager Account. Please help me in it.

**Comment by AnashOommen** [comment]
@anjanasagathiya https://developers.google.com/google-ads/api/docs/conversions/overview is a good starting point on this topic. Feel free to ask API-specific questions on https://groups.google.com/g/adwords-api?pli=1 or direct email to googleadsapi-support@google.com and you will get a faster response.

**Comment by AnashOommen** [comment]
I've fixed the README.md with details about support for .NET 5.0 and .NET 6.0.
