### ISSUE TITLE
I'm stuck... CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Nilesailor** [googleads/google-ads-dotnet#343]
Pulled the .NET client library into my VS2019 project via nuget.  Got all of my Oauth configured, but when I attempt to make any calls, I'm hitting some sort of SSL error.  Been fighting with this for a couple days and cannot find a solution.  Any help getting past this would be appreciated.

E0131 14:46:22.489678 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:1506: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0131 14:46:22.490681 0 ..\..\..\src\core\lib\security\transport\security_handshaker.cc:181: Security handshake failed: {"created":"@1643658382.490000000","description":"Handshake failed","file":"..\..\..\src\core\lib\security\transport\security_handshaker.cc","file_line":367,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}

**Comment by AnashOommen** [comment]
I'm fairly sure that's grpc stack complaining about some invalid certificate. I'll loop in someone from that project.

**Comment by Nilesailor** [comment]
Thanks Anash.  Looking forward to any suggestions.  I've tried this on multiple machines and all generate the same error.  Agree that something in the certificate handling within the client library is failing.

**Comment by jskeet** [comment]
Can I just check whether all the multiple machines have been deployed in the same way, for example are all in the same enterprise? If so, I wonder whether it's an issue with some centrally-controlled certificates. If you're able to try on a machine which would have been entirely differently configured (e.g. a personal machine) and ideally on a different network, that would rule some things out. (The gRPC stack used here is the same one we use for the Google Cloud Client Libraries, and I don't think I've seen any similar reports, so I suspect it's *something* context-specific.)

**Comment by Nilesailor** [comment]
Finally figured this out... phew! The corporate firewall was not playing nice with gRPC.  Once I isolated this, I was able to work with our security folks to address the issue.
