### ISSUE TITLE
Question- Google Ads Client Library is supported .NET core 6.0 or not?

### ISSUE THREAD

**Issue by anjanasagathiya** [googleads/google-ads-dotnet#344]
Can you tell that Google Ads Client Library is supported .NET core 6.0 or not? If it is not supported then suggest me another third party library or another way in which I can use .Net core 6.0 app.

**Comment by anjanasagathiya** [comment]
@AnashOommen Can you please reply of this question?

**Comment by AnashOommen** [comment]
@anjanasagathiya I responded on #340, but copying the response here as well.

The library works fine with .net6 apps because it supports netstandard 2.0. The library hasn't been explicitly built for .net6 target though, I hope to add support for the next release.
