### ISSUE TITLE
TotalResultCount equals 0 when SummaryRowSetting =SummaryRowOnly

### ISSUE THREAD

**Issue by momolasd** [googleads/google-ads-dotnet#345]
**Describe the bug:**

Hello, when i'm requesting only summary row, total result count is always set to 0

**Steps to Reproduce:**

![image](https://user-images.githubusercontent.com/11518432/152358250-cfcff512-617c-41d2-a2f8-dd6284b105a3.png)

**Expected behavior:**

I expect to get total rows count instead 0

**Client library version and API version:**
Client library version: 10.2.0
Google Ads API version: V9
.NET version:  .Net Core 3.1
Operating system (Linux, Windows, ...) and version (if the bug is platform-specific): windows 10

**Comment by AnashOommen** [comment]
Hi,

Could you pls turn on logging as per the instructions at https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging and share a request ID? I don't think this is a client library issue, but rather an API issue. I can investigate it though.

**Comment by momolasd** [comment]
Hello,

Here is the request id : 90GFittw6BKOTonM4hLFng

Thank you @AnashOommen

**Comment by AnashOommen** [comment]
@momolasd This behaviour is working as intended, since the server retrieves only aggregation of rows instead of the whole set of rows when you request [SummaryRowSetting =SummaryRowOnly.
