### ISSUE TITLE
Visual Studio setup project dependencies error

### ISSUE THREAD

**Issue by rhw2012** [googleads/google-ads-dotnet#348]
I’m using Visual Studio 2019 (C# language, .NET Framework 4.8).  To try to troubleshoot this issue, I created a new solution and added a class library project and added a reference to Google.Ads.GoogleAds version 10.2.0.0 using Nuget.  It installed all the necessary dependencies (or so I thought).  I created a setup project and added the primary output from the class library project.  Cleaned and rebuilt.  It does successfully build; however, I noticed several lines like below:

WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.CONFIGURATION.ABSTRACTIONS' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.PRIMITIVES' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.PRIMITIVES' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.FileProviders.Physical.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.FILEPROVIDERS.ABSTRACTIONS' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.FileProviders.Physical.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.FILESYSTEMGLOBBING' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.FileProviders.Physical.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.FILEPROVIDERS.ABSTRACTIONS' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.Json.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.CONFIGURATION' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.Json.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.CONFIGURATION.ABSTRACTIONS' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.Json.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.CONFIGURATION.FILEEXTENSIONS' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.Json.dll'
WARNING: Unable to find dependency 'SYSTEM.MEMORY' (Signature='CC7B13FFCD2DDD51' Version='4.0.1.0') of assembly 'Microsoft.Extensions.Primitives.dll'
WARNING: Unable to find dependency 'SYSTEM.BUFFERS' (Signature='CC7B13FFCD2DDD51' Version='4.0.2.0') of assembly 'Grpc.Core.dll'
WARNING: Unable to find dependency 'GOOGLE.PROTOBUF' (Signature='A7D26565BAC4D604' Version='3.15.8.0') of assembly 'Google.Api.Gax.Grpc.dll'
WARNING: Unable to find dependency 'SYSTEM.VALUETUPLE' (Signature='CC7B13FFCD2DDD51' Version='4.0.2.0') of assembly 'Google.Api.Gax.Grpc.dll'
WARNING: Unable to find dependency 'SYSTEM.THREADING.TASKS.EXTENSIONS' (Signature='CC7B13FFCD2DDD51' Version='4.2.0.0') of assembly 'Google.Api.Gax.Grpc.dll'
WARNING: Unable to find dependency 'SYSTEM.VALUETUPLE' (Signature='CC7B13FFCD2DDD51' Version='4.0.2.0') of assembly 'Google.Api.Gax.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'Google.Protobuf.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.CONFIGURATION' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.FileExtensions.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.FILEPROVIDERS.PHYSICAL' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.FileExtensions.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.FILEPROVIDERS.ABSTRACTIONS' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.FileExtensions.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.PRIMITIVES' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.FileExtensions.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.CONFIGURATION.ABSTRACTIONS' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.FileExtensions.dll'
WARNING: Unable to find dependency 'SYSTEM.THREADING.TASKS.EXTENSIONS' (Signature='CC7B13FFCD2DDD51' Version='4.2.0.0') of assembly 'Microsoft.Bcl.AsyncInterfaces.dll'
WARNING: Unable to find dependency 'GOOGLE.APIS.AUTH' (Signature='4B01FA6E34DB77AB' Version='1.46.0.0') of assembly 'Grpc.Auth.dll'
WARNING: Unable to find dependency 'GOOGLE.PROTOBUF' (Signature='A7D26565BAC4D604' Version='3.15.8.0') of assembly 'Google.Api.CommonProtos.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'System.Threading.Tasks.Extensions.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.PRIMITIVES' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.FileProviders.Abstractions.dll'
WARNING: Unable to find dependency 'MICROSOFT.EXTENSIONS.PRIMITIVES' (Signature='ADB9793829DDAE60' Version='3.1.0.0') of assembly 'Microsoft.Extensions.Configuration.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'System.Memory.dll'
WARNING: Unable to find dependency 'GOOGLE.PROTOBUF' (Signature='A7D26565BAC4D604' Version='3.15.8.0') of assembly 'Google.LongRunning.dll'
WARNING: Unable to find dependency 'SYSTEM.VALUETUPLE' (Signature='CC7B13FFCD2DDD51' Version='4.0.2.0') of assembly 'System.Text.Json.dll'
WARNING: Unable to find dependency 'SYSTEM.THREADING.TASKS.EXTENSIONS' (Signature='CC7B13FFCD2DDD51' Version='4.2.0.0') of assembly 'System.Text.Json.dll'
WARNING: Unable to find dependency 'SYSTEM.BUFFERS' (Signature='CC7B13FFCD2DDD51' Version='4.0.2.0') of assembly 'System.Text.Json.dll'

If I try to run actual code using GoogleAds with these errors present in the log, it will not run.  What am I missing?  Am I using the wrong versions of the dependencies?

**Comment by AnashOommen** [comment]
Perhaps try doing a .NET restore once more and do a rebuild? I tried with Visual Studio 2022 and .NET Framework 4.8, and it works fine. I've attached a project. Could you compare with Visual Studio 2019 to see if there's a difference? There shouldn't be any, except for the tool version number that Visual Studio adds.
[ConsoleApp1.zip](https://github.com/googleads/google-ads-dotnet/files/8074179/ConsoleApp1.zip)

You need to run 

```sh
nuget restore ConsoleApp1.sln
msbuild ConsoleApp1.sln
```

**Comment by rhw2012** [comment]
Added nuget reference to Google.Ads.GoogleAds version 10.2.0 using the default install options (dependency lowest).

If you try to debug the test demo (no setup project used), then the code crashes on line 26 of Class1.cs.  The error is in the comments directly below that line.

Using the setup project and installing to an IIS server into a .net 4 integrated application pool,

Trying the setup project, I got a 404 error when trying to browse the WebForm1.aspx page from a web browser.

Executed Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r

Now I get:

Could not load file or assembly 'System.ValueTuple' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

These lines are in the output when using the setup project:

WARNING: Unable to find dependency 'GOOGLE.APIS.AUTH' (Signature='4B01FA6E34DB77AB' Version='1.46.0.0') of assembly 'Grpc.Auth.dll'
WARNING: Unable to find dependency 'GOOGLE.PROTOBUF' (Signature='A7D26565BAC4D604' Version='3.15.8.0') of assembly 'Google.LongRunning.dll'
WARNING: Unable to find dependency 'GOOGLE.PROTOBUF' (Signature='A7D26565BAC4D604' Version='3.15.8.0') of assembly 'Google.Api.Gax.Grpc.dll'
WARNING: Unable to find dependency 'GOOGLE.PROTOBUF' (Signature='A7D26565BAC4D604' Version='3.15.8.0') of assembly 'Google.Api.CommonProtos.dll'

**Comment by AnashOommen** [comment]
HI,

The attachment is missing... Could you upload again?

**Comment by rhw2012** [comment]
I did add it.  Did your email system strip it out?

I just uploaded it to GitHub.

**Comment by AnashOommen** [comment]
Downloaded it from GitHub. Checking...

**Comment by AnashOommen** [comment]
I think the problem is that when you create an ASP.NET (.NET Framework) project that depends on a class library that depends on Google.Ads.GoogleAds, then Visual Studio doesn't add the necessary binding redirects in the ASP.NET project's Web.config. The Google libraries are all compiled at different points in time, so sometimes they cause dependency conflicts.

Try adding the following node to your Web.config. The easiest way to get a full up-to-date list is as follows.

1. Create an empty ASP.NET project.
2. Add a nuget reference to Google.Ads.GoogleAds.
3. Copy whatever redirects that Visual Studio inserts into your `Web.config` and put it in your web application's `Web.config`.

I'll add some documentation around this topic, if this workaround fixes the issue for you.

```xml
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Protobuf" publicKeyToken="a7d26565bac4d604" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.18.1.0" newVersion="3.18.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.53.0.0" newVersion="1.53.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Primitives" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Configuration.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.FileProviders.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.FileSystemGlobbing" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Configuration" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.FileProviders.Physical" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Configuration.FileExtensions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.9.0" newVersion="3.1.9.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by rhw2012** [comment]
I think I finally got past the error by installing GoogleAds into my ASP.NET project; however, I’m still getting a lot of lines starting with WARNING: “Unable to find dependency …”.

Now I’m getting the following authentication error when using your sample query:

{"Status(StatusCode=\"PermissionDenied\", Detail=\"The caller does not have permission\", DebugException=\"Grpc.Core.Internal.CoreErrorDetailException: ***@***.***\",\"description\":\"Error received from peer ipv4:142.251.32.202:443\",\"file\":\"..\\..\\..\\src\\core\\lib\\surface\\call.cc\",\"file_line\":1070,\"grpc_message\":\"The caller does not have permission\",\"grpc_status\":7}\")"}

We are migrating from Adwords to GoogleAds.  We previously used a Service Account to access Adwords and would like to do the same for GoogleAds.

We already have the Google Workspace domain set up.  We already have the API developer token.  The Google Ads API has been enabled.  We already have the service account with domain-wide authority using scope (https://www.googleapis.com/auth/adwords).  We already have the Google Ads user.  What am I missing?

We tried using configuration files and your code sample but neither authenticates correctly.  From your sample, we are sending: DeveloperToken, LoginCustomerId, OAuth2ClientId, OAuth2Mode (set to OAuth2Flow.SERVICE_ACCOUNT), OAuth2PrnEmail, and OAuth2SecretsJsonPath.

What else should I try?

**Comment by AnashOommen** [comment]
Hi,

Could you turn on logging by using the instructions at https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging and post a request ID? I suspect that this is due to a wrong `login-customer-id` being used, but the easiest way to verify that is by looking at the logs.

**Comment by AnashOommen** [comment]
@rhw2012 what email address did you use to generate the OAuth2 access token? Can you mail me directly at anash@google.com? The request itself seems fine, but the error suggests you are using the wrong email address.

**Comment by rhw2012** [comment]
It ended up being a wrong login-customer-id as you suspected.  Thanks for your suggestion.
