### ISSUE TITLE
ETA on V10 Support?

### ISSUE THREAD

**Issue by JonathanStack** [googleads/google-ads-dotnet#349]
Hello,

Just wondering if you have an estimated release date for API V10 support? Looks like the other libraries already have it as of a few days ago.

Thanks!

**Comment by AnashOommen** [comment]
HI @JonathanStack I plan to release it by end of this week. Investigating a minor performance regression...

**Comment by AnashOommen** [comment]
Library v11.0 has added support for API version v10.0.0.
