### ISSUE TITLE
directly set OAuth2PrivateKey

### ISSUE THREAD

**Issue by KLuuKer** [googleads/google-ads-dotnet#350]
I would like to directly set the `OAuth2PrivateKey` instead of loading it through `OAuth2SecretsJsonPath`

We store all (api\crypto) keys in a secure storage solution (for example Azure Key Vault) and transport them encrypted to the machine where its being used.
We have a large multitenant solution and don't wish to leave\copy around a bunch of files on disk

Please provide a option to directly set the PrivateKey, as a string or maybe allow me to directly give a `RSAParameters`
Another option would be to allow me to set the `ServiceAccountCredential` and have me use the available public api

**Comment by AnashOommen** [comment]
Hi @KLuuKer the easiest way is to extent GoogleAdsConfig class and override CreateCredentials method to write your own implementation. Then pass an instance of that class everywhere as applicable.

https://github.com/googleads/google-ads-dotnet/blob/main/src/Config/GoogleAdsConfig.cs#L691
