### ISSUE TITLE
Make all classes serializable and deserializable with System.Text.Json

### ISSUE THREAD

**Issue by mayerwin** [googleads/google-ads-dotnet#353]
**Describe the problem you are trying to solve**
I am trying to serialize API responses (e.g. GoogleAdsRow) for caching purposes using System.Text.Json (.NET 6). Unfortunately, it is impossible to deserialize correctly as a lot of fields are missing public writers, or some public writers all write to the same underlying private field (of `object` type), causing data to be erased when another public field for the same private field has a null value.

**Describe the solution you would like**
It'd be good if the types could be improved to support serialization and deserialization, as was the case with the Google AdWords API.

**Comment by AnashOommen** [comment]
Hi @mayerwin,

The serialization / deserialization for protobuf objects work a bit differently. Here's an example.

```c#
GoogleAdsRow row = new GoogleAdsRow()
{
    Campaign = new Campaign()
    {
        Id = 123,
        Name = "Campaign 1",
        ResourceName = ResourceNames.Campaign(1234567890, 123)
    }
};
// Serialize to JSON and back. Human readable and friendly, but less efficient.
string json = JsonFormatter.Default.Format(row);
row = GoogleAdsRow.Parser.ParseJson(json);

// Serialize to bytes and back. Machine readable and less friendly, but more efficient.
byte[] bytes = row.ToByteArray();
row = GoogleAdsRow.Parser.ParseFrom(bytes);
```

I'll improve the client library documentation.

**Comment by mayerwin** [comment]
Fantastic, thanks!

**Comment by mayerwin** [comment]
Fantastics, thanks! How would you best serialize a `List<GoogleAdsRow>`?
