### ISSUE TITLE
Timezone for segments.date

### ISSUE THREAD

**Issue by sommmen** [googleads/google-ads-dotnet#354]
**What is your question?**

Hello, I'm running some reports using `Services.V10.GoogleAdsService`:

``` csharp
var query =
    "SELECT campaign.id, campaign.name, campaign.advertising_channel_type, campaign.status, metrics.impressions, " +
    "metrics.clicks, metrics.ctr, metrics.average_cpc, metrics.cost_micros, metrics.all_conversions_value, " +
    "segments.date " +
    "FROM campaign " +
    $"WHERE segments.date >= '{startDateString}' " +
    $"AND segments.date < '{endDateString}' " +
    "ORDER BY campaign.id";
``` 

I'm segmenting via `segments.date` to get daily reports - i need these daily reports to be segmented by Amsterdam time or W. Europe Standard Time - i cant really find a timezone option anywhere ind the docs or in the code.

I'm looking for something akin to https://docs.microsoft.com/en-us/advertising/guides/reports?view=bingads-13#reptimezones in the google ads api.

I.e.
How can i run reports daily for a specific time zone?

**Comment by AnashOommen** [comment]
Google Ads API assumes the timezone of the account, and there isn't currently a way to override this behaviour. This is a limitation of how Google Ads itself, and not to do with the client library.
