### ISSUE TITLE
No Exception thrown, and no logging on AWQL query with Error on v10

### ISSUE THREAD

**Issue by Zweitze** [googleads/google-ads-dotnet#359]
When firing an (apparently) broken GoogleAdsServiceClient.SearchStream, some AWQL queries call the delegate with an empty result, and an RequestId. The request itself, nor the response are logged.

For instance this code:
```csharp
string Query = string.Format(@"
SELECT
    campaign.id, campaign.name, campaign.serving_status, campaign.start_date,
    ad_group.id, ad_group.name,
    ad_group_criterion.criterion_id, user_list.name,
    ad_group_criterion.final_urls, ad_group_criterion.final_mobile_urls
FROM ad_group_audience_view
WHERE
    campaign.status = 'ENABLED' AND
    campaign.serving_status IN ('SERVING', 'PENDING') AND
    campaign.start_date < '{0:yyyyMMdd}' AND
    ad_group.status = 'ENABLED' AND
    ad_group_criterion.status = 'ENABLED' AND
    ad_group_criterion.approval_status != 'DISAPPROVED'
", DateTime.Today.AddDays(7d));

GoogleAdsServiceClient gas = gaclient.GetService(
    Services.V10.GoogleAdsService);
gas.SearchStream(CustomerId.ToString(), Query,
    delegate (SearchGoogleAdsStreamResponse resp)
{
    Console.WriteLine("RequestId: \"{0}\"", resp.RequestId);
});
```

Note: when using V9, you get an Exception with error InvalidArgument - no information which argument is invalid, but that appears to be an issue in the API.

**Client library version and API version:**
Client library version: 11.0.0.0
Google Ads API version: V10
.NET version: .NET Framework 4.7.2
Operating system: Windows 10 Pro 20H2, 19042.1526

**Request/Response Logs:** NOT GENERATED AT ANY LEVEL

**Anything else we should know about your project / environment**
The AWQL query appears to be invalid, although it is accepted by the AWQL query validator. That's a problem of the API, described here: https://groups.google.com/g/adwords-api/c/a2Kbod3J-uQ/m/DZQ41SBnCwAJ

The issue raised here: the request was not logged (was it even made?!) and no Exception was thrown.

**Comment by AnashOommen** [comment]
@Zweitze This is because the query is valid in v10 (I need to figure out why it fails on v9), but the result is empty. GRPC server returns an empty iterator in that case, causing the library to bypass logging altogether. You get an empty object back due to the fix for https://github.com/googleads/google-ads-dotnet/issues/197, though I didn't realize this was a wider problem.

**Comment by Zweitze** [comment]
Please note, 12 days ago this query was erroneous in v10, as confirmed by Peter Lawrence from Google Ads API team:
https://groups.google.com/g/adwords-api/c/a2Kbod3J-uQ/m/DZQ41SBnCwAJ

It's too bad the behavior of Google Ads API keeps changing within version.

Anyway, is it also possible to ensure that SearchGoogleAdsStreamResponse.RequestId is always filled? In my use-case standard (file-based) logging is not possible in production, and right now there's no time to figure out how to reroute the logs. Instead we save RequestId in a database.
