### ISSUE TITLE
Need to whitelist the Google ads api urls used by library on our production server

### ISSUE THREAD

**Issue by ArvindMaster** [googleads/google-ads-dotnet#384]
Hi Google leads api team,

Can you please share me the urls that the client library
https://github.com/googleads/google-ads-dotnet/

accesses to connect to google ads api internally. I am unable to locate the urls.

Right now when I run project on my local machine it works fine, But when I run same on server where external urls are blocked, it doesnt work and gives error

Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1649326888.179000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1649326888.179000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":147,"grpc_status":14}]}")

Currently I have identified the below urls which are already whitelisted by my infra team but still getting above error message.

Whitelisted urls
 
https://www.googleapis.com
https://accounts.google.com
https://googleads.googleapis.com
https://gaagl.page.link

Kindly help me whitelist the respective urls used by this library to connect Google ads account and modify customer match.

Pl share me list of the urls that I should whitelist on the hosting server machine if I missed any.

**Comment by jradcliff** [comment]
Hi,

The library also makes requests to the OAuth servers at `https://oauth2.googleapis.com`.

Thanks,
Josh, Google Ads API Team

**Comment by ArvindMaster** [comment]
HI Josh ,

Whitelisted https://oauth2.googleapis.com as well but still getting same error

Thanks
Arvind

**Comment by jradcliff** [comment]
Hi Arvind,

If the logs don't contain the URLs that are still an issue, you could try enabling more verbose logging in gRPC as described at the end of this section of our logging guide:

https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging#advanced_logging

Also, if you have a stack trace from when you encounter this error, that could help pinpoint the types of requests that are failing (OAuth, Google Ads API, or something else).

Thanks,
Josh

**Comment by AnashOommen** [comment]
@ArvindMaster is this issue resolved for you?

**Comment by AnashOommen** [comment]
Closing for now, please reopen if the issue persists.
