### ISSUE TITLE
Rehydrate models with readonly RepeatedField?

### ISSUE THREAD

**Issue by petersontubini** [googleads/google-ads-dotnet#385]
Hi,

I'm working into a functionality where I'm replicating a few Assets from the campaign to another campaign in the same account level.

For that I'm storing the Assets into a database for caching and rehydrating these models so I can mutate it later.

The main issue that I'm having is that I can serialize the RepeatedFields but I can't deserialize it because it's marked as readonly:

`
private readonly RepeatedField<string> finalUrls_ = new RepeatedField<string>();
`

My question is: how can I rehydrate these models if the RepeatedFields are readonly?

**Comment by AnashOommen** [comment]
Hi @petersontubini see https://developers.google.com/google-ads/api/docs/client-libs/dotnet/working-with-protobuf?hl=en#repeated_types.
