### ISSUE TITLE
I cannot specify the Values field on a new StructuredSnippetAsset becaus it is "get" only.

### ISSUE THREAD

**Issue by rr180** [googleads/google-ads-dotnet#389]
**Describe the bug:**

**Steps to Reproduce:**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]

**Expected behavior:**

**Client library version and API version:**
Client library version:
Google Ads API version:
.NET version:
Operating system (Linux, Windows, ...) and version (if the bug is platform-specific):

**Request/Response Logs:**

**Anything else we should know about your project / environment**

**Comment by AnashOommen** [comment]
See https://github.com/googleads/google-ads-dotnet/issues/346 for a fix.

**Comment by rr180** [comment]
Hello. I do not believe #346 is a fix for my issue. #346 refers to a Mutate Request and the solution you provided is to use a different request (in that case, a Mutate Campaigns Request).
But my problem is that the StructuredSnippetAsset cannot be created in C# because the only field it needs (the Values field) is read only. It is not a Mutate Request problem, it is a class problem (the StructuredSnippetAsset would be created, in my routine, inside a Batch Request, which is working fine for the rest of the items I'm creating - campaign, adgroups, CalloutAssets, etc).
Could you please have a look at the StructuredSnippetAsset class?

![image](https://user-images.githubusercontent.com/6710642/167663603-e928083e-1a08-4733-8495-5cdbec21772f.png)


Thanks!

**Comment by AnashOommen** [comment]
It's the same thing; basically the question is how to populate a RepeatedField.

```c#
// Newer C# versions with collection initialization syntax.
StructuredSnippetAsset asset = new StructuredSnippetAsset()
{
    Values = { "foo", "bar" }
 };
 // Older C# versions.
 asset.Values.AddRange( {"foo", "bar"} );
```

**Comment by rr180** [comment]
Thanks!
