### ISSUE TITLE
Create/Update Feed Fails with "Request contains an invalid argument" error

### ISSUE THREAD

**Issue by washamdev** [googleads/google-ads-dotnet#390]
**Describe the bug:**
We are in the process of migrating the .NET Nuget package for "Google.Ads.GoogleAds" from version "9.0.0" to version "11.0.1". After doing so, we are now making a call like the code below in _Steps to Reproduce_ in order to update a Feed.

Instead of getting a `MutateFeedsResponse` back, it blows up with the following exception error every time:

> {"Status(StatusCode=\"InvalidArgument\", Detail=\"Request contains an invalid argument.\", DebugException=\"Grpc.Core.Internal.CoreErrorDetailException: {\"created\":\"@1651768123.016000000\",\"description\":\"Error received from peer ipv4:172.***.**.**:443\",\"file\":\"..\\..\\..\\src\\core\\lib\\surface\\call.cc\",\"file_line\":1070,\"grpc_message\":\"Request contains an invalid argument.\",\"grpc_status\":3}\")"}

Note that we can _load_ Feeds just fine by passing a query to `await googleAdsService.SearchStreamAsync`, so we are able to connect to the API and run queries, but we have been unable to create or update anything since switching to 11.0.1. This same `Request contains an invalid argument` error is generated for both creates and updates.

**Steps to Reproduce:**
```
using Google.Ads.GoogleAds;
using Google.Ads.GoogleAds.Lib;
using Google.Ads.GoogleAds.Util;
using Google.Ads.GoogleAds.V10.Services;

// We load the Google.Ads.GoogleAds.V10.Resources.Feed into the "feed" variable here.
var operation = new FeedOperation() {
    Update = feed,
    UpdateMask = FieldMasks.AllSetFieldsOf(feed)
};
var googleAdsConfig = new GoogleAdsConfig() {
    DeveloperToken = "***********************",
    LoginCustomerId = "124*******",
    OAuth2Mode = OAuth2Flow.APPLICATION,
    OAuth2ClientId = "***********************************.apps.googleusercontent.com",
    OAuth2ClientSecret = "***************************",
    OAuth2RefreshToken = "*******************************************************************************************************",
};
var googleAdsClient = new GoogleAdsClient(googleAdsConfig);
FeedServiceClient serviceClient = googleAdsClient.GetService(Services.V10.FeedService);
long customerId = 0; // We are storing this customer ID on our end when we create the Feed, so the 0 here is just a placeholder.

// This method blows up with the "InvalidArgument" error 100% of the time.
MutateFeedsResponse response = await serviceClient.MutateFeedsAsync(customerId.ToString(), new List<FeedOperation>() { operation }, cancellationToken);
```

Here is what the `feed` object looks like before it's sent to the MutateFeedsAsync method:

![image](https://user-images.githubusercontent.com/4692325/167164998-8f9b7e68-de48-4f4b-aa4f-fe89bf669ab8.png)

Here is what the FeedOperation looks like:

![image](https://user-images.githubusercontent.com/4692325/167165755-e47d4b1f-44d5-4b3f-8dab-a5d047d1b749.png)

**Expected behavior:**
Should update the Feed, like it used to in version 9 of the Nuget package.

**Client library version and API version:**
Client library version: 11.0.1
Google Ads API version: 10
.NET version: .NET Core 3.1
Operating system (Linux, Windows, ...) and version (if the bug is platform-specific):

**Request/Response Logs:**
I enabled detailed logging, but when I accessed the file after these errors, the request doesn't appear there. The last request I see logged is actually to `Method Name: /google.ads.googleads.v10.services.GoogleAdsService/SearchStream`. There are no requests logged to Mutate a Feed. The last `SearchStream` request had request ID `gWZW4d6ou032M0e8eZ5EWw`, if that matters (shouldn't matter, since we can GET just fine).

**Anything else we should know about your project / environment**

Here are all the Nuget packages we have installed in this project, in case one of the other ones could be messing something up:

![image](https://user-images.githubusercontent.com/4692325/167166208-d777fe3a-2cea-4f2a-b61b-3b158e527481.png)

**Comment by AnashOommen** [comment]
Since the call is Async, the logs get a while to be written (i.e. it is not synchronized).

Could you share the request-id? It is also part of the GoogleAdsException. Add the exception to the Visual Studio watch and expand the fields.
