### ISSUE TITLE
Enum values do NOT match documentation

### ISSUE THREAD

**Issue by Nilesailor** [googleads/google-ads-dotnet#401]
I've run into this a few times with the Google Ads API.  According to the documentation, the enum values for the WebpageConditionOperand are "UNSPECIFIED", "UNKNOWN", "URL", "CATEGORY", "PAGE_TITLE" , "PAGE_CONTENT", and "CUSTOM_LABEL" in all caps with underscores exactly as they were in the AdWords API.

https://developers.google.com/google-ads/api/reference/rpc/v10/WebpageConditionOperandEnum.WebpageConditionOperand

However, when using those enum values, an error is thrown.  In investigating, I notice that drilling down through the enum in Visual Studio where I'm using the .NET Client Library, the enum values in the client library are "Unspecified", "Unknown", "Url", "Category", "PageTitle", "PageContent", and "CustomLabel" with a mix of upper and lower case and with no underscores.  

I'm finding it really difficult to code for values where the enums in documentation do not match what is exposed by the client library.

 
![image](https://user-images.githubusercontent.com/44070742/168098490-27e4d451-8a0d-4556-aba2-50a6b1620531.png)

**Comment by AnashOommen** [comment]
@Nilesailor that's because we moved from one naming standard (Microsoft's SOAP generator - wsdl.exe) to another naming standard (Google's protobuf generator -- protoc.exe). See https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#enum. While I agree that the concern is genuine, fixing this issue is not feasible without changing the entire protobuf coding convention.

**Comment by Nilesailor** [comment]
I have all the values from the Google documentation stored in our internal database (as they have been for years as they were also used in the AdWords API).  

In order to make API calls, I pull the documented string values from our database, and cast them as follows.  Any slick ideas for still passing the documented enum values inline without writing individual converter methods for each and every one of the Google enums to convert them to the protobuf values?

Operand = (AdsClient.Enums.WebpageConditionOperandEnum.Types.WebpageConditionOperand)Enum.Parse(typeof(AdsClient.Enums.WebpageConditionOperandEnum.Types.WebpageConditionOperand), DOCUMENTED_ENUM_VALUE)
