### ISSUE TITLE
Creation of a GoogleAdsException for test purpose do not work anymore with v12

### ISSUE THREAD

**Issue by cbeauchemin** [googleads/google-ads-dotnet#402]
I was using the following line to create a fake exception for my mock:

var exception = GoogleAdsException.Create(new RpcException(Status.DefaultCancelled));

It do not work anymore.

trailer object inside the lib is empty. Its searching for the key 
google.ads.googleads.v9.errors.googleadsfailure-bin

Object Lib\AdsBaseException.cs, line 98

**Comment by danny-quinn** [comment]
I too use this method in tests to mock failures and have run into this bug when using 12.0.0

I have reverted to version 11.0.1 for the time being.

// Works in 11.0.1 not 12.0.0 
var g = GoogleAdsException.Create(
		new RpcException(
			new Status(StatusCode.PermissionDenied,"Error Detail")
		)
	);

**Comment by cbeauchemin** [comment]
@danny-quinn i've found an alternative which is less pretty but work until its fixed

private GoogleAdsException GetFakeGoogleAdsException()
  {
      var metadata = new Metadata();
      metadata.Add("google.ads.googleads.v9.errors.googleadsfailure-bin", new byte[0]);
      var rcpException = new RpcException(Status.DefaultCancelled, metadata, "Some message");
      return (GoogleAdsException)GoogleAdsException.Create(rcpException);
  }

**Comment by AnashOommen** [comment]
Fixed in 12.1.0.
