### ISSUE TITLE
FieldMasks.AllSetFieldsOf() returns incorrectly formatted field mask

### ISSUE THREAD

**Issue by LRBelin** [googleads/google-ads-dotnet#406]
**Describe the bug:** When I call FieldMasks.AllSetFieldsOf() for an updatable asset (for instance Call Asset) the field masks are returned without the proper prefix.  I expect callAsset.phoneNumber but I get phoneNumber only. 

**Steps to Reproduce:**
var call = new CallAsset
                {
                    PhoneNumber = proposedCall.PhoneNumber,
                    CountryCode = "US"
                };

                operations.Add(new AssetOperation
                {
                    UpdateMask = FieldMasks.AllSetFieldsOf(call),
                    Update = new Google.Ads.GoogleAds.V10.Resources.Asset
                    {
                        CallAsset = call,
                        Type = AssetTypeEnum.Types.AssetType.Call,
                        ResourceName = knownCall.Resource
                    }
                });

 results in "updateMask": "phoneNumber,countryCode" 

**Expected behavior:**

"updateMask": "callAsset.countryCode,callAsset.phoneNumber"

**Client library version and API version:**
Client library version: 10.2
Google Ads API version: 10
.NET version: 6.0
Operating system (Linux, Windows, ...) and version (if the bug is platform-specific): Windows

**Request/Response Logs:**
GoogleAds.DetailedRequestLogs Information: 1 : [2022-05-12 13:42:04Z] - 
---------------BEGIN API CALL---------------

Request
-------

Method Name: /google.ads.googleads.v10.services.AssetService/MutateAssets
Host: https://googleads.googleapis.com
Headers: {
  "x-goog-api-client": "gl-dotnet/6.0.0 gapic/11.0.1 gax/3.5.0+6cfcac416e08abe8a5d580f8d87095c9fdba577e grpc/2.43.0 gccl/11.0.1",
  "developer-token": "REDACTED",
  "login-customer-id": "4155429433",
  "x-goog-request-params": "customer_id=4093050793"
}

{ "customerId": "4093050793", "operations": [ { "update": { "resourceName": "customers/4093050793/assets/39136298540", "type": "CALL", "callAsset": { "countryCode": "US", "phoneNumber": "(301) 543-5432" } }, "updateMask": "phoneNumber,countryCode" } ] }

Response
--------
Headers: {
  "request-id": "9fN0o8-pdQbepakH9DKB_Q",
  "date": "Thu, 12 May 2022 13:42:03 GMT",
  "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
  "google.ads.googleads.v10.errors.googleadsfailure-bin": "ClIKAkACEjpUaGUgZmllbGQgbWFzayBjb250YWluZWQgYW4gaW52YWxpZCBmaWVsZDogJ2NvdW50cnlfY29kZScuIhASDgoKb3BlcmF0aW9ucxgAClIKAkACEjpUaGUgZmllbGQgbWFzayBjb250YWluZWQgYW4gaW52YWxpZCBmaWVsZDogJ3Bob25lX251bWJlcicuIhASDgoKb3BlcmF0aW9ucxgAEhY5Zk4wbzgtcGRRYmVwYWtIOURLQl9R",
  "grpc-status-details-bin": "CAMSJVJlcXVlc3QgY29udGFpbnMgYW4gaW52YWxpZCBhcmd1bWVudC4aiQIKRHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmFkcy5nb29nbGVhZHMudjEwLmVycm9ycy5Hb29nbGVBZHNGYWlsdXJlEsABClIKAkACEjpUaGUgZmllbGQgbWFzayBjb250YWluZWQgYW4gaW52YWxpZCBmaWVsZDogJ2NvdW50cnlfY29kZScuIhASDgoKb3BlcmF0aW9ucxgAClIKAkACEjpUaGUgZmllbGQgbWFzayBjb250YWluZWQgYW4gaW52YWxpZCBmaWVsZDogJ3Bob25lX251bWJlcicuIhASDgoKb3BlcmF0aW9ucxgAEhY5Zk4wbzgtcGRRYmVwYWtIOURLQl9R"
}

Fault: {
  "StatusCode": 3,
  "Details": "Request contains an invalid argument.",
  "RequestId": "9fN0o8-pdQbepakH9DKB_Q",
  "Failure": {
    "errors": [
      {
        "errorCode": {
          "fieldMaskError": "FIELD_NOT_FOUND"
        },
        "message": "The field mask contained an invalid field: 'country_code'.",
        "location": {
          "fieldPathElements": [
            {
              "fieldName": "operations",
              "index": 0
            }
          ]
        }
      },
      {
        "errorCode": {
          "fieldMaskError": "FIELD_NOT_FOUND"
        },
        "message": "The field mask contained an invalid field: 'phone_number'.",
        "location": {
          "fieldPathElements": [
            {
              "fieldName": "operations",
              "index": 0
            }
          ]
        }
      }
    ],
    "requestId": "9fN0o8-pdQbepakH9DKB_Q"
  }
}
----------------END API CALL----------------

**Anything else we should know about your project / environment**

**Comment by LRBelin** [comment]
I just tested v12 of the .net client and can confirm this is happening in that version as well.

**Comment by AnashOommen** [comment]
The fieldMask should be calculated relative to the object you set on the `Update` field.

So you need to modify your code like this:

```c#
var call = new CallAsset
{
    PhoneNumber = proposedCall.PhoneNumber,
    CountryCode = "US"
};

var asset = new Google.Ads.GoogleAds.V10.Resources.Asset
{
    CallAsset = call,
    Type = AssetTypeEnum.Types.AssetType.Call,
    ResourceName = knownCall.Resource
 }

operations.Add(new AssetOperation
{
    UpdateMask = FieldMasks.AllSetFieldsOf(asset),
    Update = asset
});
```
