### ISSUE TITLE
API LOGGING

### ISSUE THREAD

**Issue by TalOvedPlus500** [googleads/google-ads-dotnet#408]
Hi,
I tried to follow after this guid: https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging 
when I tried to put this code in my service:
![image](https://user-images.githubusercontent.com/106529449/170978403-1251714a-8fd8-4696-920e-adf6b1be61a8.png)

I am getting an error:
System.TypeInitializationException: The type initializer for 'Google.Ads.GoogleAds.V10.Services.GoogleAdsServiceReflection' threw an exception. ---> System.Threading.ThreadAbortException: Exception of type 'System.Threading.ThreadAbortException' was thrown.

Do you know why?
and how can I solve this?

Best Regards,

**Comment by AnashOommen** [comment]
Closing for now, pls reopen if this is replicable.
