### ISSUE TITLE
failed to connect to all addresses

### ISSUE THREAD

**Issue by scamner** [googleads/google-ads-dotnet#409]
I am trying to build an integration using the "UploadCallConversions" endpoint, but I keep getting the below error.

Grpc.Core.RpcException: 'Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1654641331.716000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1654641331.716000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")'

This is on my development laptop that does not use a proxy server and even happens if I drop off my VPN.

**Comment by AnashOommen** [comment]
Hi @scamner https://github.com/grpc/grpc/issues/23273 seems relevant here. It is a connectivity issue, likely triggered when your VPN connection drops.

**Comment by scamner** [comment]
Actually, I was saying it's an issue while on VPN and after I disconnect. My VPN is not dropping, I was just eliminating that as a possibility. So, the issue persists.
