### ISSUE TITLE
Request ID available in response

### ISSUE THREAD

**Issue by AlesSturala** [googleads/google-ads-dotnet#410]
Hello,

Almost every time there is a question about the API or a problem reported on the GAds forum, we are asked to provide the Request ID. This is relatively easy to do locally on our dev machines by looking into the GAds log. But in production there are millions of requests every hour and it's impossible to map from the summary log which query of the rows belongs to the API request that we want to have investigated.

Therefore we're unable to provide Request IDs for queries run anywhere else other than in our local env. Would it be possible to provide the Request ID in the response of the API call? Both, for the successful and failed. Then we can include it in our own application logs.

**Comment by AnashOommen** [comment]
@AlesSturala for reporting, you can do something like:

```c#
// Get the GoogleAdsService.
GoogleAdsServiceClient googleAdsService = client.GetService(
    Services.V11.GoogleAdsService);

// Create a query that will retrieve all campaigns.
string query = @"SELECT
                campaign.id,
                campaign.name,
                campaign.network_settings.target_content_network
            FROM campaign
            ORDER BY campaign.id";

try
{
    // Issue a search request.
    googleAdsService.SearchStream(customerId.ToString(), query,
        delegate (SearchGoogleAdsStreamResponse resp)
        {
            // Note: This field may not be populated in every single callback; it is typically in the very last callback.
            string requestId = resp.RequestId;
        }
    );
}
catch (GoogleAdsException e)
{
    string requestId = e.RequestId;
    throw;
}
```

**Comment by AlesSturala** [comment]
Thank you Anash. We were using _googleAdsService.Search()_ which doesn't have the RequestId but we will change to SearchStream().

What about DeadlineExceeded exceptions, is there a way to get the RequestID? That is a _RpcException_ within an _AggregateException_.
