### ISSUE TITLE
v11 and MediaUtilities

### ISSUE THREAD

**Issue by javicha** [googleads/google-ads-dotnet#415]
Hello everyone!

I just upgraded from v10 to v11. I am checking that some classes that I am using change namespaces. They are the following:
OAuth2Flow, FieldMask and MediaUtilities.

In v10, it was necessary to import Google.Ads.GoogleAds.Util. Now in v11 it gives compilation error, and it is necessary to import Google.Ads.Gax.Util.

I would like to confirm with you that the behavior is exactly the same in v11 as it is in v10, despite this namespace change.

Thank you very much

**Comment by AnashOommen** [comment]
@javicha yes, the behaviour is identical, I refactored it so that the utilities can be reused for other APIs, and also because I have to worry less about the stable parts of the code if it is in its own assembly. See https://github.com/googleads/google-ads-dotnet/blob/main/CHANGELOG.md#1200.
