### ISSUE TITLE
Failed to create conversion action for MCC account (with many accounts)

### ISSUE THREAD

**Issue by netizi** [googleads/google-ads-dotnet#417]
Hi. 

using -
Client library version:  12.1.0.0
Google Ads API version:V11
.NET version: 4.7.2

code snippet :

        ConversionActionServiceClient conversionActionService =
      _user.GetService(Services.V11.ConversionActionService);

        // Add a conversion action.
        ConversionAction conversionAction = new ConversionAction()
        {
            Name = "S2S - Phone Calls" ,
            Category = Google.Ads.GoogleAds.V11.Enums.ConversionActionCategoryEnum.Types.ConversionActionCategory.Default,
            Type = Google.Ads.GoogleAds.V11.Enums.ConversionActionTypeEnum.Types.ConversionActionType.UploadCalls,
            Status = Google.Ads.GoogleAds.V11.Enums.ConversionActionStatusEnum.Types.ConversionActionStatus.Enabled,
            ValueSettings = new ConversionAction.Types.ValueSettings()
            {
                DefaultValue = 1,
                AlwaysUseDefaultValue = true
            },
            Origin = Google.Ads.GoogleAds.V11.Enums.ConversionOriginEnum.Types.ConversionOrigin.Website,
           
        };
  CallSettings callSettings = CallSettings.FromExpiration(
                 Expiration.FromTimeout(TimeSpan.FromMilliseconds(3600000)));

        // Create the operation.
        ConversionActionOperation operation = new ConversionActionOperation()
        {
            Create = conversionAction
        };

        try
        {
            // Create the conversion action.
            MutateConversionActionsResponse response =
                conversionActionService.MutateConversionActions(_user.Config.LoginCustomerId,
                        new ConversionActionOperation[] { operation },callSettings);

            // Display the results.
            foreach (MutateConversionActionResult newConversionAction in response.Results)
            {
                _log.WriteLine("New conversion action with resource name = " +newConversionAction.ResourceName+" was added.");
            }
        }
        catch (GoogleAdsException ex)
        {
            if (ex.StatusCode == StatusCode.DeadlineExceeded)
            {
                Console.WriteLine("The server streaming call did not complete before the " +
                    "timeout.");
            }
            else
            {
                throw;
            }
        }

Request
-------

Method Name: /google.ads.googleads.v11.services.ConversionActionService/MutateConversionActions
Host: https://googleads.googleapis.com
Headers: {
  "x-goog-api-client": "gl-dotnet/4.0.30319 gapic/12.1.0 gax/3.5.0+6cfcac416e08abe8a5d580f8d87095c9fdba577e grpc/2.46.3 gccl/12.1.0 pb/3.21.1+569a0517fadd90707713fc0c24f24b1da1d174a4",
  "developer-token": "REDACTED",
  "login-customer-id": "xxxx",
  "x-goog-request-params": "customer_id=xxxx"
}

{ "customerId": "xxxx", "operations": [ { "create": { "status": "ENABLED", "type": "UPLOAD_CALLS", "category": "DEFAULT", "valueSettings": { "defaultValue": 1, "alwaysUseDefaultValue": true }, "name": "S2S - Phone Calls", "origin": "WEBSITE" } } ] }

Response
--------
Headers: {}

Fault: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Stream removed", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1655965506.874000000","description":"Error received from peer ipv4:172.217.19.42:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1070,"grpc_message":"Stream removed","grpc_status":2}")
----------------END API CALL----------------

NOTE: the same call works fine for the test MCC it is a matter of number of accounts under MCC.

**Comment by AnashOommen** [comment]
Does the call work without the expiration?

**Comment by netizi** [comment]
while I used it with my MCC  test  which has less accounts

**Comment by AnashOommen** [comment]
hi @netizi could you please send a fresh log to googleadsapi-support@google.com and add an Attn: anash@google.com? Pls refer this issue and ask that the support ticket be assigned to me.

I'll close the issue here because I may need additional details that cannot be shared over a public GitHub tracker.
