### ISSUE TITLE
How to enable AverageCpcMicros on GenerateHistoricalMetrics in V11's KeywordPlanService?

### ISSUE THREAD

**Issue by axtens** [googleads/google-ads-dotnet#425]
**What is your question?**
I am making a request for historical data using the `GenerateHistoricalMetrics` method on the `Services.V11.KeywordPlanService` service. In the results that are returned the `HasAverageCpcMicros` field is false and therefore there is nothing but zero in `AverageCpcMicros`. What do I have to add to my KeywordPlan to enable this value?

For reference, my sources are publicly available on [github](https://github.com/axtens/Plugin_GoogleAds_Metrics), and a [full trace log](https://github.com/googleads/google-ads-dotnet/files/9129102/STATS_2022-07-18-02-01-31-1103.log) and the [output JSON](https://github.com/googleads/google-ads-dotnet/files/9129104/stats.json.txt) are attached

**Comment by axtens** [comment]
> If you want to include the average_cpc_micros in response, then as initially mentioned by my colleague (Carmela), you will need to set the include_average_cpc as true in the KeywordPlanService.GenerateHistoricalMetrics request. Please note that the historical_metrics_options is an object of the KeywordPlanService.GenerateHistoricalMetrics not just by the keywords ideas. This is the configuration that is missing in your request so the average cpc is missing as well in the response.

>Unfortunately, there is no sample code that illustrate setting of this field in KeywordPlanService.GenerateHistoricalMetrics. With this, I would suggest reaching out to the author of the .Net client library via this link to know how you can implement the said field in the KeywordPlanService.GenerateHistoricalMetrics. They are more equipped to provide support on code related concerns.

>Regards,
>Ernie John
>Google Ads API Team

**Comment by AnashOommen** [comment]
@axtens we will add a new code example in the next release. Thanks for bringing this up.

**Comment by AnashOommen** [comment]
See https://github.com/googleads/google-ads-dotnet/blob/main/Google.Ads.GoogleAds/examples/Planning/GenerateHistoricMetrics.cs.
