### ISSUE TITLE
Reach for products other than YouTube?

### ISSUE THREAD

**Issue by axtens** [googleads/google-ads-dotnet#429]
In the image there is a "Reach" value in the Google Ads Keyword Plan. Is there a way to calculate / generate this in C#?
![Reach](https://user-images.githubusercontent.com/209621/180733735-9cc52e75-0aaa-4beb-ae2f-657a70399e81.png)

**Comment by AnashOommen** [comment]
Hi @axtens Could you please ask this question on the Google Ads API forum instead? https://groups.google.com/g/adwords-api
