### ISSUE TITLE
Logging to console

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [googleads/google-ads-dotnet#432]
Hello,

When using the client library for dotnet I can include more detailed logging like this:
```
TraceUtilities.Configure(TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE,
                 "C:\\Logs\\simply_summary_logs_20220713.log", SourceLevels.All);
```

But how do I log this to the console? I don’t want to write to a file. For instance, I am deploying this as part of an AWS Lambda/Azure Function. We just want to log to the console. Is this possible? For example in Azure Function we would like to ingest the logs into Application Insights. Even better would be if it part of some ILogger extension.

Thanks

**Comment by Raibaz** [comment]
You can log to the console by using 

```
TraceUtilities.Configure(TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE,
                Console.Out, System.Diagnostics.SourceLevels.All);
```

This should allow you to ingest the logs being written to console in Application Insights.
