### ISSUE TITLE
Strong name signature could not be verified in .NET Framework 4.7.2 app

### ISSUE THREAD

**Issue by hakimio** [googleads/google-ads-dotnet#437]
**Describe the bug:**

I am getting the following error when trying to use the library with .NET Framework 4.7.2:
```
Could not load file or assembly 'Google.Ads.Gax' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

**Steps to Reproduce:**
Try to use the latest version of the library in `.NET Framework 4.7.2` application.

**Expected behavior:**

No errors.

**Client library version and API version:**
Client library version: **13.0.1**
Google Ads API version: **11**
.NET version: **4.7.2**
Operating system: **Windows 10**
Google.Ads.Gax: **1.0.2**

**Comment by hakimio** [comment]
Version **12.1.0** with Google.Ads.Gax: **1.0.1** works as expected.

**Comment by AnashOommen** [comment]
@hakimio Thank you for catching this issue. I switched the compilation process from Windows to Linux in this release, so perhaps the assembly signing process broke. I'll take a look. For now, kindly stay on v12.1.0.

**Comment by hakimio** [comment]
Thanks for fixing this so fast.
