### ISSUE TITLE
Unable to connect to google ads in dotnet client library

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [googleads/google-ads-dotnet#448]
Hello,
I started seeing the below error which I am not quit sure what is causing. Unfortunately I don’t have those detailed logs because it fails before sending any audience lists.

It fails when I call the google ads api to search for an existing user list. Also, it is not possible to produce detailed or summary logs in a cloud environment like Azure App Service. This line of code:
`TraceUtilities.Configure(TraceUtilities.SUMMARY_REQUEST_LOGS_SOURCE, Console.Out, SourceLevels.All); `
Does not send the logs to Application Insights so I cannot view them there or in the log stream.
The only way to generate them is when running locally and save the logs to my local disk. It would be great feature improvement if your logging system hooked into ILogger instead. Unfortunately I don't encounter this error when running locally.

This is the complete error. I am a bit stuck on how to proceed.

`2022-08-25T16:58:24.733 [Error] An error Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1661446703.532000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1661446703.532000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":147,"grpc_status":14}]}") occurred when creating customer match!Grpc.Core.RpcException : Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1661446703.532000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1661446703.532000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":147,"grpc_status":14}]}")at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Google.Ads.Gax.Interceptors.UnaryRpcInterceptor.Intercept[T,TResponse](??)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.<>c__DisplayClass4_0.<CallAsync>g__WaitAndCallHandlers|0[TRequest,TResponse](??)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<WithRetry>b__0[TRequest,TResponse](??)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Google.Api.Gax.Grpc.ResponseAsyncEnumerable`3.ResponseAsyncEnumerator.MoveNextAsync[TRequest,TResponse,TResource]()at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Google.Api.Gax.Grpc.ResourceEnumerator`2.MoveNextAsync[TResource,TResponse]()at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async MarketingAnalyticsCLV.CustomerLifetimeValue.Google.GoogleAds.GoogleAdsCustomerMatch.SearchUserListByName(String userListName) at C:\general-repos\Apoteket\MarketingAnalyticsCLV\CustomerLifetimeValue\Google\GoogleAds\GoogleAdsCustomerMatch.cs : 42at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async MarketingAnalyticsCLV.CustomerLifetimeValue.Google.GoogleAds.GoogleAdsCustomerMatch.SearchUserListByName(String userListName) at C:\general-repos\Apoteket\MarketingAnalyticsCLV\CustomerLifetimeValue\Google\GoogleAds\GoogleAdsCustomerMatch.cs : 42at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async MarketingAnalyticsCLV.CustomerLifetimeValue.Google.Service.GoogleCustomerLifetimeValueService.SendCustomerListAsync(CustomerMatchRequestModel clvBatchesRequestModel,Dictionary`2 customerLists) at C:\general-repos\Apoteket\MarketingAnalyticsCLV\CustomerLifetimeValue\Google\Service\GoogleCustomerLifetimeValueService.cs : 35 
`

**Comment by AnashOommen** [comment]
Hi @SoucianceEqdamRashti Could you try with the latest version of Google Ads API library (v14.0.0)? This seems a bit like https://github.com/googleads/google-ads-dotnet/issues/416 to me. 

Also, could you post a few details?

* The OS and version.
* The library version
* The .NET Runtime version
* Any additional details such as the type of project (console, windows, ASP.NET, etc.)

**Comment by AnashOommen** [comment]
Closing this issue since the developer hasn't responded. Pls reopen if the issue persists.
