### ISSUE TITLE
Method not found (Grpc.Auth.GoogleGrpcCredentials.ToChannelCredential) calling GetService on a GoogleAdsClient

### ISSUE THREAD

**Issue by axtens** [googleads/google-ads-dotnet#449]
**Describe the bug:**
Attempting to call the GetService method on an instance of GoogleAdsClient throws the following error:
```
Method not found: 'Grpc.Core.ChannelCredentials Grpc.Auth.GoogleGrpcCredentials.ToChannelCredentials(Google.Apis.Auth.OAuth2.ITokenAccess)'.
```
**Steps to Reproduce:**
```
        public static ReachPlanServiceClient GetReachPlanServiceClient(GoogleAdsClient client, bool debug = false)
        {
            if (debug) Debugger.Launch();
            return client.GetService(Services.V11.ReachPlanService);
        }
```
**Expected behavior:**
Expecting a ReachPlanServiceClient instance to be returned.

**API version:**
Google Ads API version: 
Google.Ads.GoogleAds 14.0.0
.NET version: 
4.8
Operating system (Linux, Windows, ...) and version (if the bug is platform-specific):
Windows 11

**Request/Response Logs:**
Not available. Error occurs before logs receive data.

**Anything else we should know about your project / environment**
 * Console app. 
 * [Repo](https://github.com/axtens/Plugin_GoogleAds_Metrics/blob/master/Reach.cs) containing adaption of https://developers.google.com/google-ads/api/docs/samples/forecast-reach Run method.
 * A full OAuth was done to make sure client was properly instantiated

**Comment by AnashOommen** [comment]
I can't seem to replicate this issue. Could you check in a command line example also? That way I can just build the repo as is.

**Comment by AnashOommen** [comment]
Closing for now, since this isn't replicable.

**Comment by axtens** [comment]
It's on the list to do, but I'm the only developer in the company. So yes, close. If/when I get to it ...
