### ISSUE TITLE
StatusCode="DeadlineExceeded", Detail="Deadline Exceeded"

### ISSUE THREAD

**Issue by Azami1002** [googleads/google-ads-dotnet#457]
Hi
Method Function - 

public List<CampaignSetting> GetCampaignDetails(string AccountID)
        {
            GoogleAdsClient client = new GoogleAdsClient();
            List<CampaignSetting> Campaign = new List<CampaignSetting>();
            GoogleAdsServiceClient googleAdsService = client.GetService(Services.V11.GoogleAdsService);
            SearchGoogleAdsRequest request = new SearchGoogleAdsRequest()
            {
                PageSize = PAGE_SIZE,
                Query = @"SELECT
                           campaign.id,
                            campaign.name,
                            campaign.status,
                            campaign.start_date,
                            campaign.end_date,
                            campaign.network_settings.target_content_network
                        FROM campaign
                        ORDER BY campaign.id",
                CustomerId = AccountID
            };
            object sync = new Object();
            try
            {
                PagedEnumerable<SearchGoogleAdsResponse, GoogleAdsRow> searchPagedResponse = googleAdsService.Search(request);
                Parallel.ForEach(searchPagedResponse, response =>
                {
                    lock (sync)
                    {
                        Campaign.Add(new CampaignSetting()
                        {
                            CampaignID = response.Campaign.Id.ToString(),
                            Name = response.Campaign.Name,
                            Status = response.Campaign.Status.ToString(),
                            StartDate = response.Campaign.StartDate,
                            EndDate = response.Campaign.EndDate,
                        });
                    }

                });
            }
            catch(Exception ee)
            {

            }
            return Campaign.OrderByDescending(c => c.StartDate).ToList();
        }

 **I'm getting below error -** 
Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1662987408.741000000","description":"Deadline Exceeded","file":"..\..\..\src\core\ext\filters\deadline\deadline_filter.cc","file_line":81,"grpc_status":4}")

**Comment by AnashOommen** [comment]
Hi @Azami1002 perhaps it is a combination of a large account + the use of paging. Can you use Streaming instead? Here's an example: https://github.com/googleads/google-ads-dotnet/blob/main/Google.Ads.GoogleAds/examples/BasicOperations/GetKeywords.cs#L88

**Comment by Azami1002** [comment]
I have tried with this example (https://github.com/googleads/google-ads-dotnet/blob/main/Google.Ads.GoogleAds/examples/BasicOperations/GetKeywords.cs#L88) - But Still getting same error  - "Detail="Deadline Exceeded", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1663045617.542000000","description":"Deadline Exceeded","file":"..\..\..\src\core\ext\filters\deadline\deadline_filter.cc","file_line":81,"grpc_status":4}") "
