### ISSUE TITLE
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. Inner Stack Trace

### ISSUE THREAD

**Issue by RentCafeDev** [googleads/google-ads-dotnet#461]
Getting the following error when trying to get Account performance data.  See attached for code snippet.

Error Occurred Message: One or more errors occurred. Stack Trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)   at Google.Ads.GoogleAds.V11.Services.GoogleAdsServiceClient.SearchStream(SearchGoogleAdsStreamRequest request, Action`1 responseCallback, CallSettings callSettings)   at xxx.GetQueryResultStream(Int64 CustomerId, String Query) in D:\xxxxx\xxx\xx\xxxxx\xxx\xxx\xxx.cs:line 3137   at xxx.xxx(Int64 CustomerId, DateTime startDate, DateTime endDate, List`1& accountPerformanceList) in D:\xxxxx\xxx\xx\xxxxx\xxx\xxx\xxx.cs:line 2095   at xxx.xxx(DateTime StartDate, DateTime EndDate, Boolean CorporateSubSite) in D:\xxxxx\xxx\xx\xxxxx\xxx\xxx\xxx.vb:line 258   at xx.xxx.xxx() in D:\xxxxx\xxx\xx\xxxxx\xxx\xxx\xxx.vb:line 36   at xxx.xxx.OnExecute(IJobExecutionContext context) in D:\xxxxx\xxx\xx\xxxxx\xxx\xxx\xx.vb:line 27   at xxxx.yJob.Execute(IJobExecutionContext context) in D:\xxxxx\xxx\xx\xxxxx\xxx\xxx\\yJob.vb:line 10 Source: mscorlib Inner Message 1: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. Inner Stack Trace 1:    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)   at System.Reflection.Assembly.GetTypes()   at Google.Ads.Gax.Interceptors.UnaryRpcInterceptor.FindAdsExceptionType[TResponse](RpcException rpcException)   at Google.Ads.Gax.Interceptors.UnaryRpcInterceptor.ParseRpcException[TResponse](RpcException rpcException)   at Google.Ads.Gax.Interceptors.UnaryRpcInterceptor.ParseTaskException[TResponse](AggregateException e)   at Google.Ads.Gax.Interceptors.StreamingRpcInterceptor`1.<MoveNext>d__5.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Google.Api.Gax.Grpc.AsyncRes\\xxxxx\xxx\xx\xxxxx\xxx\xxx\yJob.vb:line 10 Source: mscorlib Inner Message 1: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. Inner Stack Trace 1:    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)   at System.Reflection.Assembly.GetTypes()   at Google.Ads.Gax.Interceptors.UnaryRpcInterceptor.FindAdsExceptionType[TResponse](RpcException rpcException)   at Google.Ads.Gax.Interceptors.UnaryRpcInterceptor.ParseRpcException[TResponse](RpcException rpcException)   at Google.Ads.Gax.Interceptors.UnaryRpcInterceptor.ParseTaskException[TResponse](AggregateException e)   at Google.Ads.Gax.Interceptors.StreamingRpcInterceptor`1.<MoveNext>d__5.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Google.Api.Gax.Grpc.AsyncResponseStream`1.<MoveNextAsync>d__8.MoveNext() in /_/Google.Api.Gax.Grpc/AsyncponseStream`1.<MoveNextAsync>d__8.MoveNext() in /_/Google.Api.Gax.Grpc/AsyncResponseStream.cs:line 71--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Google.Ads.GoogleAds.V11.Services.GoogleAdsServiceClient.<>c__DisplayClass32_0.<<SearchStreamAsync>b__0>d.MoveNext() Source 1: mscorlib    

For issues that are related to the Google Ad
![QueryResultStreamMethod](https://user-images.githubusercontent.com/48969143/191814815-2ccfa7f8-0949-4ec4-9073-8d08bd8dcb03.png)
![AccountPerformanceDataMethog](https://user-images.githubusercontent.com/48969143/191814819-2213289d-0529-4413-8ca4-25edaf333367.png)
s API itself and not specific to this library, please reach out to one of our support channels: https://developers.google.com/google-ads/api/support. 

The request and responses are not being logged.

**Comment by AnashOommen** [comment]
@RentCafeDev were you able to capture a request ID? Looks to me like a reflection error when trying to deserialize an error -- perhaps because the error returned a type that's not published in the client library?

Or perhaps you could share the code snippet and the customer ID of the account against which the call was made and I can try replicating this issue?

**Comment by RentCafeDev** [comment]
@AnashOommen

Thank you for your response.  I cannot capture the request ID because the error is a regular exception not a GoogleAdsException, but the error is happening on "googleAdsService.SearchStream(CustomerId.ToString(), Query," see code snipped in original post.

**Comment by AnashOommen** [comment]
Hi @RentCafeDev,

I see it, but (a) I don't have the full query because the {StartDate} and {EndDate} are function parameters (b) This could be account-specific, so I might not be able to replicate this in my personal test account.

Can you please do a few steps for me?
1) If you can place a breakpoint before making the API call, and share the query from the Visual Studio watch?
2) Share the value of CustomerId
3) Customer ID of the account that owns your developer token
4) The approximate timestamp where you made this API call.

I can try locating it from our server logs.

These are sensitive information, so do not share them on this tracker. Kindly send these details to googleadsapi-support@google.com in a new email and address it to me (Attn: Anash). Mention in the email that this was redirected from https://github.com/googleads/google-ads-dotnet/issues/461, so kindly escalate to Anash@. I'll follow up from our support queue.

**Comment by RentCafeDev** [comment]
@AnashOommen,

I only have this issue on our production servers, which I cannot debug.  What would cause a specific client account to produce the error?

Below is the query:

select metrics.impressions, metrics.conversions, metrics.cost_micros, metrics.cost_per_conversion, metrics.ctr, metrics.clicks, segments.device, segments.ad_network_type
,  metrics.average_cpc, metrics.search_budget_lost_impression_share, metrics.search_impression_share, segments.date 
FROM customer WHERE segments.device IN ('DESKTOP', 'MOBILE', 'TABLET') AND segments.date between 20220917 and 20220922 and metrics.impressions > 0

The estimated time of the call was 10:07:06 AM this morning.

**Comment by AnashOommen** [comment]
Google Ads use an experiment framework, where accounts are sometimes enabled / disabled for specific features which are not generally available. That's one reason I can think of.

Could you also share the customer ID of the account that hold your developer token? Don't share the developer token itself. I may be able to narrow down my query with both these information.

**Comment by AnashOommen** [comment]
Closing due to lack of comms. Pls reopen if the issue persists.
