### ISSUE TITLE
Accessing enums in Google.Ads.GoogleAds.V11

### ISSUE THREAD

**Issue by axtens** [googleads/google-ads-dotnet#465]
**What is your question?**
I have code running the following snippet
```
                    PagedEnumerable<SearchGoogleAdsResponse, GoogleAdsRow> searchPagedResponse =
                        googleAdsService.Search(request);

                    foreach (GoogleAdsRow googleAdsRow in searchPagedResponse)
                    {
```
Currently I'm serializing the googleAdsRow to JSON and back again so that I can programmatically access the values. There's probably a much better way but I haven't figured it out yet.

When I'm in Visual Studio's debugger I can access the values in googleAdsRow by entering things like `googleAdsRow.Customer.Id`. But suppose I'm passing in a string describing that path. How do I evaluate the contents of googleAdsRow so as to access Customer's Id and Campaign's Id and AdGroupAd.PolicySummary.ReviewStatus?

The goal is to be able return to the caller the text representation of the various enums in the result set.

**Comment by axtens** [comment]
I have discovered a workaround: Call the API directly using RestSharp. Thus the javascript values for the enums are returned as text strings and do not disappear into the enums of the C# abstractions.

**Comment by AnashOommen** [comment]
You could use `ProtobufUtilities.GetOriginalEnumFieldName(HelloStatus.InProcess));` to get the actual enum name as defined in the proto file. Substitute the actual enum value instead of `HelloStatus.InProcess`.
