### ISSUE TITLE
Is sharing of  specific user list supported?

### ISSUE THREAD

**Issue by qhd1996** [googleads/google-ads-dotnet#471]
I would like to ask if the sharing of one or some user list is supported
Based on the previous doc, if a manager account chooses to share user list to a sub account, then all of his user list is shared.

**Comment by AnashOommen** [comment]
Hi,

Could you repost on the main forum? https://groups.google.com/g/adwords-api. Pls provide screenshots from the UI highlighting the specific feature you are trying to locate in the API.
