### ISSUE TITLE
Missing PartialFailure in UploadClickConversionsResponse

### ISSUE THREAD

**Issue by davestitz** [googleads/google-ads-dotnet#473]
When submitting a UploadClickConversionsRequest via the UploadClickConversions API method with a list of operations using PartialFailure = true, the response does not follow the standard response that places the errors in the index order of the submitted operations.

The response.Results does organize the results in order of the operations but in the event that one of the results fails, the GetErrorsByOperationIndex helper method fails.

When inspecting the response errors, the returned result list starts back at a zero index so you cannot extract the specific error in relation to the operation list submitted.

`response.PartialFailure.Errors[operationIndex].ErrorCode`

Example API call:
![GetErrorsByOperationIndex-Error](https://user-images.githubusercontent.com/1083612/200978782-c9aca099-d6f2-4ecf-bc9e-2f11d0428af0.png)

**Comment by AnashOommen** [comment]
Hi Dave,

Could you post a redacted request / response to help me debug this issue? I'm not sure if this is a library-specific issue, but I can tell better with a log.

**Comment by davestitz** [comment]
Hi Anash,

Sure thing, I have the request / response log with my dev token redacted but I would prefer to submit this privately to ensure the my customer information is kept hidden. Should I submit this through the Google Ads Support email or send directly to you?

Thank you,

**Comment by AnashOommen** [comment]
Hi @davestitz you can email googleadsapi-support@google.com and cc me (anash@google.com). I'll close this issue here and follow up on the support email thread.
