### ISSUE TITLE
Summary and Data are not matching for Search Term View - Report

### ISSUE THREAD

**Issue by VishwanathKri** [googleads/google-ads-dotnet#474]
**Describe the bug:**

Summary and Data are not matching for Search Term View - Report

**Steps to Reproduce:**

Generate 2 reports as below with Summary Row and Without Summary Row (data)

**Full Data:**
googleAdsService.SearchStream(googleAPIDetails.CustomerId, query,
                    delegate (SearchGoogleAdsStreamResponse resp)
                    {
                        var result = resp.ToString();
                        System.IO.File.WriteAllText(@"D:\\Downloads-sdk\\SearchTermJun01-Data.json", result);
         }

**Summary Data:**
googleAdsService.SearchStream(googleAPIDetails.CustomerId, query, 
                    delegate (SearchGoogleAdsStreamResponse resp)
                    {
                        var result = resp.ToString();
                        System.IO.File.WriteAllText(@"D:\\Downloads-sdk\\SearchTermJun01-Summary.json", result);
                    }
                    , Google.Ads.GoogleAds.V12.Enums.SummaryRowSettingEnum.Types.SummaryRowSetting.SummaryRowOnly
                );

**Expected behavior:**

Clicks, costMicros and Impressions should match in both Json files.

**Client library version and API version:**
Client library version: 12
Google Ads API version: 12
.NET version: 
Operating system Windows 10

**Request/Response Logs:**

**Comment by AnashOommen** [comment]
@VishwanathKri this is not a library-specific issue, but I located the issue in the support queue and I can follow up from there.
