### ISSUE TITLE
DMA-level data for campaign reporting - Data Discrepancy

### ISSUE THREAD

**Issue by VishwanathKri** [googleads/google-ads-dotnet#475]
**Describe the bug:**

1.	Google Ads Console for June 15 and without DMA shows 52,241 Impressions and 3,071 Clicks.
a.	Google Ads Campaign API for June 15 matches.
2.	Google Ads Console for June 15 and with DMA Region and Postal Code fields added to Rows shows 42,886 Impressions and 2,557 Clicks.
a.	Google Ads API Geographic_View output shows 3,667 Impressions and 368 Clicks.
Questions:
1.	What is the difference in Impressions and Clicks for #1 and #2 above? Would the difference be when the DMA and Postal Code are "unknown"?
2.	What is the difference between #2 and 2.a? Does geographic_view specifically only show data when geo-targeting is used at the Campaign level?
a.	If so, is there Google Ads API access that includes DMA and Postal Code data without geo-targeting? For example, replicating the screenshot below and understanding and differences in data per Question #1 above.

**Steps to Reproduce:**

Campaign Query
SELECT campaign.bidding_strategy,campaign.campaign_budget,campaign.campaign_group,campaign.end_date,campaign.id,campaign.name,campaign.start_date,campaign.status,segments.date,segments.device,metrics.absolute_top_impression_percentage,metrics.active_view_impressions,metrics.active_view_measurability,metrics.active_view_measurable_cost_micros,metrics.active_view_measurable_impressions,metrics.all_conversions,metrics.all_conversions_value,metrics.clicks,metrics.cost_micros,metrics.engagements,metrics.impressions,metrics.interactions,metrics.video_views,metrics.view_through_conversions,metrics.video_quartile_p50_rate,metrics.video_quartile_p100_rate FROM campaign WHERE segments.date BETWEEN '2022-06-15' AND '2022-06-15'";

Geographic Query:
SELECT geographic_view.location_type,campaign.id,campaign.name,campaign.resource_name,ad_group.name,ad_group.id,segments.date,segments.device,segments.geo_target_city,segments.geo_target_metro,segments.geo_target_postal_code,segments.geo_target_region,metrics.all_conversions,metrics.all_conversions_value,metrics.clicks,metrics.cost_micros,metrics.impressions,metrics.interactions,metrics.video_views,metrics.view_through_conversions FROM geographic_view WHERE segments.date BETWEEN '2022-06-15' AND '2022-06-15'";

Source Code:

googleAdsService.SearchStream(CustomerID, query, 
    delegate (SearchGoogleAdsStreamResponse resp)
    {
        var result = resp.ToString();
        System.IO.File.WriteAllText(@"D:\\Downloads-sdk\\GeographicJun15-Data.json", result);
    }
);

**Expected behavior:**

Data should match for Campaign without DMA and with DMA

**Client library version and API version:**
Client library version: 12
Google Ads API version: 12
.NET version:
Operating system : Windows 10

**Request/Response Logs:**

**Comment by AnashOommen** [comment]
Hi @VishwanathKri Could you kindly email googleadsapi-support@google.com with this question? This is not a library-specific issue.
