### ISSUE TITLE
Method not found: 'System.AppDomainSetup System.AppDomain.get_SetupInformation()'at Google.Ads.Gax.Util.ConfigUtilities.GetAppConfigPath()

### ISSUE THREAD

**Issue by amithashenoy** [googleads/google-ads-dotnet#476]
HI,

**Method not found: 'System.AppDomainSetup System.AppDomain.get_SetupInformation()'. at
 Google.Ads.Gax.Util.ConfigUtilities.GetAppConfigPath()**
Getting this eror while creating  
var client = new GoogleAdsClient(); instance
using Google.Ads.GoogleAds 14.2.0 version nuget package. Any idea why m getting this error,

M using .net core 2.1 in project

i really appreciate your help

Thanks & Regards,
Amitha,

 @AnashOommen :  i am having above issue any idea, which version of package m supposed to use .

**Comment by AnashOommen** [comment]
Hi Amitha,

You need to increase your runtime requirement. The library won't work with .NET Core 2.1.

You need one of the following runtimes, or higher.
* .NET 5.0 
* .NET Standard 2.1 
* .NET Framework 4.7.2

**Comment by amithashenoy** [comment]
Ok,


Thank you
