### ISSUE TITLE
KeywordPlanIdeaServiceClient V12 works in Console application but not in ApiController 

### ISSUE THREAD

**Issue by BDDevelopment78** [googleads/google-ads-dotnet#477]
We are using KeywordPlanIdeaServiceClient V10 and now were upgrading our solution to V12.  This is the extracted chunk of code from our application.

public string Post(bool bIsCalledFromOutside = false)
{
	string strKeywords = "";
	try
	{
		GoogleAdsClient client = new GoogleAdsClient();

		KeywordPlanIdeaServiceClient keywordPlanIdeaService =
			client.GetService(Services.V12.KeywordPlanIdeaService);

		GenerateKeywordIdeasRequest request = new GenerateKeywordIdeasRequest()
		{
			CustomerId = "XXXXXXXXXXX"
		};

		var kArray = new string[] { "USA" };
		request.KeywordSeed = new KeywordSeed();
		request.KeywordSeed.Keywords.AddRange(kArray);

		request.Language = ResourceNames.LanguageConstant(1000);

		request.GeoTargetConstants.Add(ResourceNames.GeoTargetConstant(2840));

		request.KeywordPlanNetwork = KeywordPlanNetwork.GoogleSearchAndPartners;

		var response = keywordPlanIdeaService.GenerateKeywordIdeas(request);		

		foreach (GenerateKeywordIdeaResult result in response)
		{
			strKeywords += result.Text;
		}
		
		return strKeywords;
	}
	catch(Exception ex)
	{

	}

	return strKeywords;
}

The code is currently working fine in an ApiController using V10. When we upgrade it to V11 it works fine but once we move to V12 it just hangs on the foreach statement.

We did some testing in a Console application and it works fine in while using V12.

Any ideas as to what is the problem when we use V12 in ApiController ?

**Comment by AnashOommen** [comment]
Hi,

Try using the async version. The sync version is blocking in nature and
won't work for some environments that require multi thread cooperation
(e.g. web apps on Azure, WinForms, etc.)

Tx
Anash

**Comment by BDDevelopment78** [comment]
> 

Thanks for your reply. Well firstly the client call is Async. Secondly it works for V10 and V11. Thirdly Async on server side does not solve the problem as well.

**Comment by jamshidbehsudwal7** [comment]
@BDDevelopment78
