### ISSUE TITLE
Dismiss recommendation issue

### ISSUE THREAD

**Issue by nakitadog** [googleads/google-ads-dotnet#485]
I am trying to work with this example code:
https://developers.google.com/google-ads/api/samples/dismiss-recommendation#c

The issue that I'm having is the code in that C# example is looking for the following variable:  recommendationId which is of the long data type. 

There is no recommendationId that are numerical (long). They are all string values. 

What am I missing here?

I have tried to send the resource_name to execute the DismissRecommendationOperation, however, it just hangs. 

No response is ever received.

**Comment by Raibaz** [comment]
It is indeed a bug in the DismissRecommendation example, the recommendation id should be a string instead of a long.

I'll send out a PR about it.

Thanks for noticing!

**Comment by nakitadog** [comment]
What about the primary issue? 

When I call the service.DismissRecommendation() it just hangs even when I supply a correctly formatted ResourceName?

"customers/{customer_id}/recommendations/{recommendation_id}"

**Comment by nakitadog** [comment]
I was able to solve my primary issue with the service.DismissRecommendation(). 

I did pass a string for the ResourceName, however, I also had to use the Async version of the service. 

Here's my example code:

```
public async void Dismiss_Recommendation_Operation(GoogleAdsClient client, long customerId, string RecommendationResourceName){
    RecommendationServiceClient service = client.GetService(Services.V12.RecommendationService);
    DismissRecommendationOperation operation = new DismissRecommendationOperation(){
        ResourceName = RecommendationResourceName
    };
    try{
        DismissRecommendationResponse response = await service.DismissRecommendationAsync(customerId.ToString(), new DismissRecommendationOperation[] { operation });

        foreach (DismissRecommendationResult result in response.Results)
            Console.WriteLine($"Dismissed recommendation with resource name = [{result.ResourceName}].");
    }
    catch (GoogleAdsException e){
        Console.WriteLine("Failure:");
        Console.WriteLine($"Message: {e.Message}");
        Console.WriteLine($"Failure: {e.Failure}");
        Console.WriteLine($"Request ID: {e.RequestId}");
    }
}
```

My code is running from a Windows form.

**Comment by AnashOommen** [comment]
Yeah, WinForm and grpc sync methods don't play well. Pls use a sync methods.

**Comment by nakitadog** [comment]
You wrote: _"Pls use a sync methods"_

Did you mean synchronous or asynchronous?

**Comment by AnashOommen** [comment]
Please use Asynchronous methods with WinForms. Sorry, the response was from
my phone, and it decided to autocorrect.

**Comment by nakitadog** [comment]
Thank you for your reply and clarification.

**Comment by AnashOommen** [comment]
I'll add some additional documentation to clarify the issue with WinForms. This has shown up in at least 4 bugs so far.
