### ISSUE TITLE
Accessing Google Ads API in .Net 6

### ISSUE THREAD

**Issue by Swapygit** [googleads/google-ads-dotnet#486]
Hi Team,

We have .Net 6 Web API project where we are trying to consume Google Ads API. However, we are not able to do so due to some missing library reference. After we went through the documentation of [google ads api](https://developers.google.com/google-ads/api/docs/client-libs/dotnet) we noticed that the google ads api library doesn't have an explicit build target for .NET 6.0, however, you can use the library with a binary built for .NET 6.0 since netstandard2.0 is compatible with .NET 6.0. Could you please help us with where we can find this package, so that we can consume the API's.

Could you please help us with this issue.

**Comment by AnashOommen** [comment]
Hi @Swapygit is this issue solved for you? You should be able to just add direct dependency and use it. What error are you facing?

**Comment by AnashOommen** [comment]
For anyone who needs this in the future: I have attached a simple Web Api application using .NET 6.0.
[WebApplication1.zip](https://github.com/googleads/google-ads-dotnet/files/10984010/WebApplication1.zip)
