### ISSUE TITLE
Grpc Error 

### ISSUE THREAD

**Issue by nitheeshls** [googleads/google-ads-dotnet#495]
I'm Facing this error from **_past 3 weeks_**, while trying to retrieve reports for past 30 days. Here **out of 5 reports only 2 got success** and for **_remaining 3 (google_geographic_view, google_keyword_view,  google_search_term_view)_** I'm facing below error.

In addition to this, If I try to extract past 14 days, all reports are generating successfully.

But as per Business requirement I need to generate for **Past 30 days**.

One or more errors occurred. (Status(StatusCode="Unknown", Detail="Stream removed", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1679110054.275000000","description":"Error received from peer ipv4:142.251.16.95:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1070,"grpc_message":"Stream removed","grpc_status":2}"))
![image](https://user-images.githubusercontent.com/74233460/227137985-876b6602-f9fc-4e11-ab2e-82d57dea4c9b.png)

The  packages used 
![image](https://user-images.githubusercontent.com/74233460/227138282-5e99a05e-d2e5-422b-adc4-f280f44ee33c.png)

**Note: In Feb,2023 I was able to generate past 90 days data.**

Thanks for helping!!!

**Comment by AnashOommen** [comment]
@nitheeshls try increasing the timeout: E.g.

```
client.Config.Timeout = 30 * 60 * 1000; // 30 minutes.
```

**Comment by nitheeshls** [comment]
@AnashOommen the connection will remain more than 30 min also sometimes but getting the same error. Tried this solution earlier but not working. Is it because of V11.

**Comment by AnashOommen** [comment]
Possibly. v11 is going away in a day or two. Try upgrading to v13 and see how that goes.

**Comment by nitheeshls** [comment]
@AnashOommen While trying to update "Google.Ads.GoogleAds.V11.Services" to "Google.Ads.GoogleAds.V13.Services" by upgrading the package to 15.0.1 using NuGet Package manager.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Warning As Error: Detected package downgrade: Microsoft.Extensions.Logging from 6.0.0 to 3.1.31. Reference the package directly from the project to select a different version. 
 ElancoCORE-MINT-AdsAPI -> Google.Ads.GoogleAds 15.0.1 -> Google.Ads.GoogleAds.Core 2.1.0 -> Microsoft.Extensions.Logging (>= 6.0.0) 
 ElancoCORE-MINT-AdsAPI -> Microsoft.Extensions.Logging (>= 3.1.31)	ElancoCORE-MINT-AdsAPI	C:\Users\02709994\Downloads\rel-1\ElancoCORE-MINT-master\ElancoCORE-MINT-AdsAPI\ElancoCORE-MINT-AdsAPI.csproj	1	


How to Resolve this error?

**Comment by AnashOommen** [comment]
Upgrade ElancoCORE-MINT-AdsAPI dependency of Microsoft.Extensions.Logging to 6.0.0.

**Comment by nitheeshls** [comment]
@AnashOommen 
[2023-03-28T05:19:56.664Z] A host error has occurred during startup operation '813687a0-e0c7-4911-9a31-c4f98b9ef9e5'.

[2023-03-28T05:19:56.816Z] System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

after updating those two packages, facing above error while triggering the function app

**Comment by AnashOommen** [comment]
Hi @nitheeshls did your issue get solved?

**Comment by nitheeshls** [comment]
@AnashOommen No, Still the same issue. We tried with different version of Google.ads.GoogleAds >13 . But in each vesrion I'm facing same issue.

Additional help would needed if I'm missing anything.

Thanks!!

**Comment by nitheeshls** [comment]
![image](https://user-images.githubusercontent.com/74233460/229108254-d2380302-9a32-46c9-8ab3-6777793a2e94.png)
 do i need to make any changes in .net version in .csproj file, so that the error wiil by pass any suggestions

**Comment by AnashOommen** [comment]
Try taking the attachment from https://github.com/googleads/google-ads-dotnet/issues/501 and let me know how that works. It is a bundled library, and I've tried to downgrade the dependencies as much as possible.

**Comment by nitheeshls** [comment]
@AnashOommen ,Tried with the above package this time different error

[2023-04-01T14:21:52.434Z] Executed 'GoogleAPITimeTrigger' (Failed, Id=4d5510fc-1c08-41da-8a89-da6947b33ee1, Duration=4984ms)
[2023-04-01T14:21:52.436Z] System.Private.CoreLib: Exception while executing function: GoogleAPITimeTrigger. Google.Ads.GoogleAds: Method not found: 'System.String System.AppDomainSetup.get_ConfigurationFile()'.


I tried with .net 4 and above versions but failed there also different errors are coming in different versions because of dependencies.

**Comment by nitheeshls** [comment]
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String System.AppDomainSetup.get_ConfigurationFile()'.
  Source=Google.Ads.GoogleAds
  StackTrace:
   at Google.Ads.Gax.Util.ConfigUtilities.GetAppConfigPath()
   at Google.Ads.Gax.Util.ConfigUtilities.GetSection(String sectionName)
   at Google.Ads.Gax.Config.ConfigBase.ReadAppConfigSection(String sectionName)
   at Google.Ads.GoogleAds.Config.GoogleAdsConfig..ctor()
   at ElancoCORE_MINT_AdsAPI.GoogleAPITimeTrigger.Run(TimerInfo myTimer, ILogger log, ExecutionContext context) in C:\Users\02709994\Downloads\ElancoCORE-MINT-AdsAPI\GoogleAPITimeTrigger.cs:line 41
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__10.MoveNext()


GoogleAdsConfig googleAdsConfig = new GoogleAdsConfig()
            {
                DeveloperToken = AzureKeyVaultHelper.GetKeyValue("GoogleDeveloperToken", keyVaultURL),
                LoginCustomerId = AzureKeyVaultHelper.GetKeyValue("GoogleLoginCustomerId", keyVaultURL),
                OAuth2ClientId = AzureKeyVaultHelper.GetKeyValue("GoogleAPIClientId", keyVaultURL),
                OAuth2ClientSecret = AzureKeyVaultHelper.GetKeyValue("GoogleAPIClientSecret", keyVaultURL),
                OAuth2RefreshToken = AzureKeyVaultHelper.GetKeyValue("GoogleAPIRefreshToken", keyVaultURL),
            };

While debugging, it's throwing the above Exception here.
Please @AnashOommen Provide the solution for this. Thanks for Helping!!

**Comment by nitheeshls** [comment]
We need to upgrade for latest function app version
