### ISSUE TITLE
After upgrading to 15.0.0.0 and changing the asynchronous request, the Api request that needs to return data is stuck and has no response

### ISSUE THREAD

**Issue by kaizibian** [googleads/google-ads-dotnet#503]
Client library version and API version:
Client library version: 15.0.0
Google Ads API version: V13
.NET version: .NET Framework 4.7.2
Operational status: [#480](https://github.com/googleads/google-ads-dotnet/issues/480) and [#488](https://github.com/googleads/google-ads-dotnet/issues/488) have been browsed, asynchronous processing has been completed
There are problems: modifying the budget, creating an account and other operations actually complete the task but cannot receive the returned data, and it is directly stuck.

The code where the problem is:
 MutateAccountBudgetProposalResponse  response = await proposalService.MutateAccountBudgetProposalAsync(customerId.ToString(), operation);
Task<CreateCustomerClientResponse> t = customerService.CreateCustomerClientAsync(managerCustomerId.ToString(), customer);

I used the Task--> t.Wait(); and await to modify the precomputation separately. The actual pre-computation has been modified successfully, but the response cannot receive the return value, so it is stuck here;
The same goes for creating an account. The reality is successfully created, but the return value cannot be received, and the user is stuck.

However, operations such as 
Task t = googleAdsService.SearchStreamAsync(customerId.ToString(), query,delegate (SearchGoogleAdsStreamResponse resp) can obtain data normally.

public **async Task<bool>** Upaccount_budget_v(long customerId, long increaseAmount)
        {
            bool Is_there = false;

            AccountBudgetProposalServiceClient proposalService =
                client.GetService(Services.V13.AccountBudgetProposalService);
            

            AccountBudgetProposal proposal = new AccountBudgetProposal()
            {
                ProposalType = AccountBudgetProposalType.Update,
                AccountBudget = accountBudget.ResourceName,
                ProposedSpendingLimitMicros = accountBudget.ProposedSpendingLimitMicros + increaseAmount,
                ProposedSpendingLimitType = accountBudget.ProposedSpendingLimitType

            };
            
            long approved_spending_limit_micros = accountBudget.ApprovedSpendingLimitMicros;

            proposal.ProposedSpendingLimitMicros = approved_spending_limit_micros + increaseAmount;

            AccountBudgetProposalOperation operation = new AccountBudgetProposalOperation()
            {
                Create = proposal,
                UpdateMask = new FieldMask()
                {
                    Paths = { "proposed_spending_limit_micros" }
                }
            };

            try
            {

                MutateAccountBudgetProposalResponse  response = await proposalService.MutateAccountBudgetProposalAsync(
                    customerId.ToString(), operation);

                //////////////////test 2////////////////////////// 
                //Task<MutateAccountBudgetProposalResponse> t =
                //    proposalService.MutateAccountBudgetProposalAsync(customerId.ToString(), operation);

                //t.Wait();

                //MutateAccountBudgetProposalResponse response_2 = t.Result;
                

                Is_there = true;
            }
            catch (GoogleAdsException e)
             {
                Console.WriteLine("Failure:");
                Console.WriteLine($"Message: {e.Message}");
                Console.WriteLine($"Failure: {e.Failure}");
                Console.WriteLine($"Request ID: {e.RequestId}");
            }

            return Is_there;
        }

**Comment by kaizibian** [comment]
#488 Yes, 15.0.2 works for me! Thank you so much. Can you imagine the mentality of V11 deactivation countdown and V13 still not available?
[distro.zip](https://github.com/googleads/google-ads-dotnet/files/11045127/distro.zip)

**Comment by AnashOommen** [comment]
@kaizibian we are starting a release now. Will update this thread once the new library is live.

**Comment by AnashOommen** [comment]
v15.0.2 is live.

**Comment by AnashOommen** [comment]
Minor correction: You need to take **v15.0.3**.
