### ISSUE TITLE
Separate out the App.config and settings.json functionality into a separate assembly

### ISSUE THREAD

**Issue by AnashOommen** [googleads/google-ads-dotnet#507]
The library can mostly be used without an App.config and settings.json. But working with Microsoft.Extensions.* dependencies is a pain.

Let's separate out configuration functionality (through environment variables, json and config files) into a separate extensions library, so that
* Core library can be used as is (users can configure the library at runtime)
* Those who want configuration through files can add additional assembly dependency.
* We have a place to add more platform-specific functionality in the future. For instance, I really want to pull in https://github.com/googleads/google-ads-dotnet/pull/484, but that functionality is largely irrelevant for those who don't use DI and ASP.NET Core.

Some relevant bugs that made me think this way:

* https://github.com/googleads/google-ads-dotnet/issues/476
* https://github.com/googleads/google-ads-dotnet/issues/491
* https://github.com/googleads/google-ads-dotnet/issues/483

**Comment by AnashOommen** [comment]
Fixed in [v16.0.0.](https://github.com/googleads/google-ads-dotnet/releases/tag/v16.0.0)

**Comment by sommmen** [comment]
Hiya @AnashOommen - what would be the recommended way to register the GoogleAdsConfig now? I just updated and it seems GoogleAdsConfig no longer can take a Config;

![image](https://user-images.githubusercontent.com/8641495/235418720-a33b21e0-6bb8-4f3d-86c0-5da3136753ca.png)
