### ISSUE TITLE
Type registry has no descriptor for type name 'google.ads.googleads.v13.errors.GoogleAdsFailure'

### ISSUE THREAD

**Issue by rrkpt** [googleads/google-ads-dotnet#513]
Hi folks, 

Playing with your library and getting the following exception when trying to iterate through response results:
`Type registry has no descriptor for type name 'google.ads.googleads.v13.errors.GoogleAdsFailure'`
Here is what I do:
`UploadClickConversionsResponse response =
                    await conversionUploadService.UploadClickConversionsAsync(
                        new UploadClickConversionsRequest()
                        {
                            CustomerId = customerId.ToString(),
                            Conversions = { clickConversion },
                            PartialFailure = true,
                            ValidateOnly = false
                        });

                if(response.PartialFailureError != null)
                    logger.LogWarning($"PartialFailureError: {response.PartialFailureError.Code} " +
                        $"{response.PartialFailureError.Message} " +
                        $"{response.PartialFailureError.Details}");

                foreach(ClickConversionResult result in response.Results.ToList())
                {
                    logger.LogInformation($"Uploaded conversion that occurred at " +
                        $"'{result.ConversionDateTime}' from Google " +
                        $"Click ID '{result.Gclid}' to " +
                        $"'{result.ConversionAction}'.");
                }`

Any idea on this? Should I additionally register that type somehow?

**Comment by AnashOommen** [comment]
@rrkpt Which version of the library is this? What's the runtime you are using, and the platform? Is there a demo project you can attach to help us replicate the issue?

**Comment by rrkpt** [comment]
Hi @AnashOommen, thanks for the reply. I was using all latest, and the problem was that I was using some objects without proper de-serialization. My bet, issue can be closed now.
