### ISSUE TITLE
Troubles with creating PMAX campaign components

### ISSUE THREAD

**Issue by merisahakyan** [googleads/google-ads-dotnet#519]
I'm trying to create PMAX campaign using .Net library based on documentation provided [here](https://developers.google.com/google-ads/api/docs/performance-max/overview).
So campaign creation and assets creations passed successfully, but on asset group creation I'm getting bunch of errors about "headline,marketing image, square image...(and a lot more) assets are not enough". 
Errors I'm getting are - "NOT_ENOUGH_LONG_HEADLINE_ASSET",
"NOT_ENOUGH_HEADLINE_ASSET",
"NOT_ENOUGH_DESCRIPTION_ASSET",
"NOT_ENOUGH_BUSINESS_NAME_ASSET",
"NOT_ENOUGH_MARKETING_IMAGE_ASSET",
"NOT_ENOUGH_SQUARE_MARKETING_IMAGE_ASSET",
"NOT_ENOUGH_LOGO_ASSET". 
And this is in case I have successfully created all of them before trying too Create Asset Group.

I tried to use both types of Asset Group creation : with **MutateOperation** and **AssetGroupOperation**, and both were failed.
So, how can I create asset group, having already created corresponding required assets using .Net library?
I followed up all the steps in documentation, but it seems non-working solution. Can you help with this? It's not possible to create empty asset group, and also not possible to create asset group with manually given resourceName, and also not possible to link already created asset to assetGroup because in first stage of creation it's not possible to have asset group resource name. So, nothing is possible.

Here is code example which I'm using to create asset group (already having created assets)

```
var googleAdService = googleAdsClient.GetService(Services.V13.GoogleAdsService);

                var operations = new List<MutateOperation>();
 operations.Add(new MutateOperation()
                {
                    AssetGroupOperation = new AssetGroupOperation()
                    {
                        Create = new AssetGroup()
                        {
                            Name = $"CF-AdPro-{Guid.NewGuid()}",
                            Campaign = "customers/8951792349/campaigns/20213486313",
                            FinalUrls = { listingUrl },
                            FinalMobileUrls = { listingUrl },
                            Status = AssetGroupStatus.Enabled
                        }
                    }
                });


                var response = await googleAdService.MutateAsync(customerId, operations);
```

**Comment by Raibaz** [comment]
We had a temporary issue around the time you were experiencing this, and it could likely be related with the issue you are referring to.

The issue on our end has been resolved, so can you please confirm whether this is still happening to you?

**Comment by merisahakyan** [comment]
yes, now we don't have problems.

**Comment by Raibaz** [comment]
Thanks for confirming!
