### ISSUE TITLE
Campaign Tracking Settings Missing

### ISSUE THREAD

**Issue by aukevin** [googleads/google-ads-dotnet#52]
Hi,

In the documentation, Campaigns can be [queried for Tracking Settings](https://developers.google.com/google-ads/api/docs/fields/campaign#campaigntracking_settingtracking_url).

I see that in the stubs, there's a [line referencing them](https://github.com/googleads/google-ads-dotnet/blob/7e79b011cf0aa94182a7b7b988bfa0294bba9637/src/V0/Stubs/Campaign.cs#L153), but it looks like the Campaign object I get back in the GoogleAdsRow (Google.Ads.GoogleAds.V0.Resources.Campaign) does not have Tracking Settings in it.

Is there a different place to get those values in the response row?

Best,
Kevin

**Comment by AnashOommen** [comment]
Hi Kevin, 

Let me try regenerating the stubs just to make sure I didn't miss anything.

**Comment by AnashOommen** [comment]
Tracking setting is present in the latest stubs: https://github.com/googleads/google-ads-dotnet/blob/master/src/V1/Stubs/Campaign.cs#L684
