### ISSUE TITLE
Initial requests with different credentials are EXTREMELY slow at times

### ISSUE THREAD

**Issue by cleardarkz** [googleads/google-ads-dotnet#530]
Started a fresh .NET 6.0 project, installed latest Google Ads Api from NuGet (16.1.0)

Using SearchStream to find campaigns of a customer, the initial request may take up to a minute and a half (90 seconds or more), after the initial request, the speed returns to normal (around 300ms for a request/response)

This behavior has started happening ONLY on the .NET libraries, it was observed starting around 2-3months ago. Is there any way to fix this? How can we obtain normal response times?

Please advise

Thanks

**Comment by AnashOommen** [comment]
Hi @cleardarkz does this happen on the very first request (cold start), or when you switch a user (new GoogleAdsConfig and GoogleAdsClient)?

**Comment by AnashOommen** [comment]
Closing as not replicable.
