### ISSUE TITLE
Location Asset Creation via API

### ISSUE THREAD

**Issue by aukevin** [googleads/google-ads-dotnet#538]
It looks like the required MapsLocationSet field [maps_locations](https://developers.google.com/google-ads/api/reference/rpc/v14/MapsLocationSet) is [not settable](https://github.com/googleads/google-ads-dotnet/blob/73439fe7182a41790a621e2348bfa8a7259c1dcd/Google.Ads.GoogleAds/src/V14/AssetSetTypes.g.cs#L1394C1-L1396C4).

When I try to make a mutate request to create a LocationSync asset set, it says "the required repeated field was empty" when I don't set it:

```
    "errors": [
      {
        "errorCode": {
          "fieldError": "REQUIRED_NONEMPTY_LIST"
        },
        "message": "The required repeated field was empty.",
        "location": {
          "fieldPathElements": [
            {
              "fieldName": "operations",
              "index": 0
            },
            {
              "fieldName": "create"
            },
            {
              "fieldName": "location_set"
            },
            {
              "fieldName": "maps_location_set"
            },
            {
              "fieldName": "maps_locations"
            }
          ]
        }
      }
    ],
```

Is it supposed to be settable? If not, how should I go about creating a LocationSync AssetSet?

Thanks,
Kevin

**Comment by AnashOommen** [comment]
You cannot set the list, but you can modify the contents of the existing list.
