### ISSUE TITLE
Campaign-Level UrlCustomParameters -- How to add?

### ISSUE THREAD

**Issue by ChinaWendel** [googleads/google-ads-dotnet#566]
I am trying to add Campaign-level UrlCustomParameters, and unfortunately, this field on the Campaign object is read-only, so I cannot mutate it.

![unnamed](https://github.com/googleads/google-ads-dotnet/assets/101752763/e876706a-acd1-4fe7-85b8-a8f68f1cc084)

Is there another object I should be using here? Or is this a bug in the library?

**Comment by Raibaz** [comment]
You can't assign a value directly to the `UrlCustomParameter` field because it's readonly.

However, you can add values to the list of an already existing campaign:

```
Campaign campaign = new Campaign()
{
    // Initialize other fields
}
campaign.UrlCustomParameters.Add(new CustomParameter()
{
    Key = "A key for a custom parameter",
    Value = "The value for the custom parameter"
});
```

Does this make sense to you?
