### ISSUE TITLE
Grpc.Core.Internal.CoreErrorDetailException : failed to connect to all addresses

### ISSUE THREAD

**Issue by ICICI-SECURTIES** [googleads/google-ads-dotnet#570]
1. RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1720163325.643000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1720163325.643000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")

2. CoreErrorDetailException: {"created":"@1720163325.643000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1720163325.643000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}

**Version** 
Framework 4.8

Google.Apis.Auth : 1.67.0.0
Google.Apis.Core :  1.67.0.0
Google.Ads.GoogleAds :  20.1.0.0
Google.Ads.GoogleAds.Config : 2.0.0.0
Google.Api.Gax : 4.8.0.0
Google.Ads.GoogleAds.Core : 4.0.1.0

**Code :**

GoogleAdsConfig config = new GoogleAdsConfig();
                config.LoadFromDefaultAppConfigSection();
                config.UseGrpcCore = true;
                GoogleAdsClient client = new GoogleAdsClient(config);
                Options options = new Options();

 // Issues a mutate request to add the user list and prints some information.
            MutateUserListsResponse response = service.MutateUserLists(
                customerId.ToString(), new[] { operation });
            string userListResourceName = response.Results[0].ResourceName;
            Console.WriteLine($"User list with resource name '{userListResourceName}' " +
                $"was created.");
            return userListResourceName;

**App.config**

<GoogleAdsApi>
    
    <add key="Timeout" value="100000" />

    
    <add key="ProxyServer" value="http://localhost:4500/"/>
    <add key="ProxyUser" value=""/>
    <add key="ProxyPassword" value=""/>
    <add key="ProxyDomain" value=""/>

    
    <add key="DeveloperToken" value="****"/>

    
    <add key = "OAuth2Mode" value="APPLICATION"/>
    <add key = "OAuth2ClientId" value = "***" />
    <add key = "OAuth2ClientSecret" value = "***" />
    <add key = "OAuth2RefreshToken" value = "***" />
      
    <add key = "UseGrpcCore" value="true"/>
    </GoogleAdsApi>

Referral URL : https://github.com/googleads/google-ads-dotnet/blob/21487aa13c302dc064a3a712680b8914f2725253/Google.Ads.GoogleAds/examples/Remarketing/AddCustomerMatchUserList.cs#L200-L233

Please check below error : 
![image](https://github.com/user-attachments/assets/bca3bacc-299b-400c-8de8-f01558fe456f)

Can you please help us.

**Comment by Raibaz** [comment]
Looking at the error description, this seems to be a network configuration issue.

Can you make sure that your application can indeed connect to the proxy server you specified at `localhost:4500` and that `localhost` does indeed correspond to the machine where your proxy server is running?

**Comment by AnashOommen** [comment]
Grpc also uses http/2 + binary payload, so the proxy and firewall may need
to be configured to let that kind of traffic through.

**Comment by ICICI-SECURTIES** [comment]
> Looking at the error description, this seems to be a network configuration issue.
> 
> Can you make sure that your application can indeed connect to the proxy server you specified at `localhost:4500` and that `localhost` does indeed correspond to the machine where your proxy server is running?

We are developing Google ads api using console application so in that case what is the configuration is required in app.config

Is this tag (proxyserver) required for console application?

**Comment by Raibaz** [comment]
It's not required unless you have, indeed, a proxy server running at localhost:4500.

You can leave it empty if you don't.

**Comment by ICICI-SECURTIES** [comment]
Now we make it blank

**Comment by ICICI-SECURTIES** [comment]
After make it blank we are facing below issue,

**Error**
Status(StatusCode="Unavailable", Detail="DNS resolution failed for [googleads.googleapis.com:443](http://googleads.googleapis.com:443/): UNAVAILABLE: OS Error", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1721370455.961000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1721370455.961000000","description":"DNS resolution failed for [googleads.googleapis.com:443](http://googleads.googleapis.com:443/): UNAVAILABLE: OS Error","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")

![image (1)](https://github.com/user-attachments/assets/910f20b3-776c-48c8-9635-fec7f9b14789)

**Comment by Raibaz** [comment]
Still seems to be a network issue.

Can you please make sure you can resolve the DNS entry for googleads.googleapis.com from the machine you're running your application on?

**Comment by AnashOommen** [comment]
Closing as stale, since this is an old issue. Please reopen if you need more help.
