### ISSUE TITLE
Linking Manager Test Account to Test Account - managerLinkError (INVALID_CHANGE)

### ISSUE THREAD

**Issue by NickLammerskitten** [googleads/google-ads-dotnet#586]
I am trying to Link my Google Ads Manager Test Account to a Google Ads Account.
For this I have used the code of the example of the googleAdsTeam.
The Link works well in the Web with the Customer I am trying to link. When I am trying to link it with the API, I am getting an error.

As described in the docs, I have an Google Ads Manager Account with a developer token and a Test Google Ads Manager Account, which is using the same developer token. (As Described in the Google Ads Web)

The error is the following one:

` {
  "StatusCode": 3,
  "Details": "Request contains an invalid argument.",
  "RequestId": "qv4ro4X21o6WZmOtcxT5uA",
  "Failure": {
    "errors": [
      {
        "errorCode": {
          "managerLinkError": "INVALID_CHANGE"
        },
        "message": "The change for mutate link is invalid.",
        "location": {
          "fieldPathElements": [
            {
              "fieldName": "operation"
            }
          ]
        }
      }
    ],
    "requestId": "qv4ro4X21o6WZmOtcxT5uA"
  }
} `  

It seems to me that there is an error in the customerClientLink

This is the GoogleAdsService:
` using Google.Ads.Gax.Config;
using Google.Ads.GoogleAds.Config;
using Google.Ads.GoogleAds.Lib;

namespace Sellerverse.shared.googleAdsService;

public class GoogleAdsService
{
    private readonly string _managerCustomerId;
    private readonly GoogleAdsClient _client;

    public GoogleAdsService()
    {
        _managerCustomerId = Environment.GetEnvironmentVariable("GOOGLE_ADS_MANAGER_ID") ??
                             throw new InvalidOperationException("GOOGLE_ADS_MANAGER_ID not set");

        var config = new GoogleAdsConfig
        {
            DeveloperToken = Environment.GetEnvironmentVariable("GOOGLE_ADS_API_DEVELOPER_TOKEN"),
            OAuth2Mode = OAuth2Flow.SERVICE_ACCOUNT,
            OAuth2SecretsJsonPath = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS"),
            LoginCustomerId = Environment.GetEnvironmentVariable("GOOGLE_ADS_MANAGER_ID")
        };

        _client = new GoogleAdsClient(config);
    }

    public GoogleAdsClient GetClient()
    {
        return _client;
    }

    public string GetManagerCustomerId()
    {
        return _managerCustomerId;
    }
} `

This seems to me correct, because there is no Authentication error or Authorization error which comes normally first and because it came already, but I fixed this already.

This is the GoogleAdsApiAdapter, which is the class which communicates with the API

`using Google.Ads.GoogleAds;
using Google.Ads.GoogleAds.V18.Errors;
using Google.Ads.GoogleAds.V18.Resources;
using Google.Ads.GoogleAds.V18.Services;
using Sellerverse.GoogleAdsIntegration.domain;
using Sellerverse.shareddomain;
using Sellerverse.shareddomain.domain;
using GoogleAdsService = Sellerverse.shared.googleAdsService.GoogleAdsService;
using static Google.Ads.GoogleAds.V18.Enums.ManagerLinkStatusEnum.Types;

namespace Sellerverse.GoogleAdsIntegration.infrastructure.adapters.api;

public class GoogleAdsApiAdapter : IGoogleAdsApiAdapter
{
    private readonly GoogleAdsService _googleAdsService;

    public GoogleAdsApiAdapter(GoogleAdsService googleAdsService)
    {
        _googleAdsService = googleAdsService;
    }

    public async Task LinkGoogleAdsAccount(TenantId tenantId, GoogleAdsCustomerId customerId)
    {
        var client = _googleAdsService.GetClient();
        var managerCustomerId = _googleAdsService.GetManagerCustomerId();
        var numericCustomerId = customerId.GetNumericCustomerId();

        var customerClientLinkService = client.GetService(Services.V18.CustomerClientLinkService);
        var customerClientLink = new CustomerClientLink
        {
            ClientCustomer = ResourceNames.Customer(numericCustomerId),
            Status = ManagerLinkStatus.Pending
        };

        var customerClientLinkOperation = new CustomerClientLinkOperation
        {
            Create = customerClientLink
        };

        try
        {
            var response = await customerClientLinkService.MutateCustomerClientLinkAsync(managerCustomerId,
                customerClientLinkOperation);
            Console.WriteLine(response.Result.ResourceName);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw new Exception("Failed to link Google Ads account");
        }
    }
}`

The managerCustomerId is in the Format '2167491529' as well as the numericCustomerId.
As you can expect, the managerCustomerId is my manager test account and the customerId is the test account to link with.

Is there anything I am not seeing at this point?

Small addition: I have tried this with dotnet 6.0 and 7.0 with the GoogleAds.Ads.GoogleAds NuGet with the version 21.1.1 which officially supports dotnet 6.0.

Thank you for your help.

**Comment by Raibaz** [comment]
Hi, this seems to be an issue with the API itself rather than with the .NET client library.

Can you please reach out to the API support team [here](https://developers.google.com/google-ads/api/support/api-issues)?

Thanks!
