### ISSUE TITLE
client.GetService(Services.V1.KeywordPlanIdeaService)

### ISSUE THREAD

**Issue by sqreem-geno** [googleads/google-ads-dotnet#60]
_"Could not load file or assembly 'Google.Apis.Auth, Version=1.21.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The system cannot find the file specified."_

Every time I call client.GetService function, I experience the above error. Then after resolving taht dependency problem, another one will pop up and then there goes the chain of dependency problem/inconsistency.

**Comment by AnashOommen** [comment]
How are you getting your dependency? Are you using Nuget?

**Comment by sqreem-geno** [comment]
It still has the same error. I turned on already automatic binding redirection. I'm doing a Class Library (.NET Framework) if this would help.

**Comment by AnashOommen** [comment]
Are you depending on Google.Apis.Auth in a way other than through the client library dependency? Could you pls share a simple project showing your dependencies so I can take a look?

**Comment by AnashOommen** [comment]
Is this issue resolved?

**Comment by jaycatapang** [comment]
Hi! This is the packages.config file of the library. All dependencies were downloaded straight from NuGet. When I created a console app with the same functions and all dependencies were downloaded from NuGet as well, all seems to go well. 

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Google.Ads.GoogleAds" version="1.0.0" targetFramework="net47" />
  <package id="Google.Api.CommonProtos" version="1.5.0" targetFramework="net47" />
  <package id="Google.Api.Gax" version="2.6.0" targetFramework="net47" />
  <package id="Google.Api.Gax.Grpc" version="2.6.0" targetFramework="net47" />
  <package id="Google.Apis" version="1.38.0" targetFramework="net47" />
  <package id="Google.Apis.Auth" version="1.38.0" targetFramework="net47" />
  <package id="Google.Apis.Core" version="1.38.0" targetFramework="net47" />
  <package id="Google.LongRunning" version="1.1.0" targetFramework="net47" />
  <package id="Google.Protobuf" version="3.6.1" targetFramework="net47" />
  <package id="Grpc.Auth" version="1.18.0" targetFramework="net47" />
  <package id="Grpc.Core" version="1.19.0" targetFramework="net47" />
  <package id="Grpc.Core.Api" version="1.19.0" targetFramework="net47" />
  <package id="Microsoft.Extensions.Configuration" version="1.1.2" targetFramework="net47" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="1.1.2" targetFramework="net47" />
  <package id="Microsoft.Extensions.Primitives" version="1.1.1" targetFramework="net47" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net47" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="net47" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net47" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net47" />
  <package id="System.Collections" version="4.3.0" targetFramework="net47" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net47" />
  <package id="System.Console" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net47" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net47" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net47" />
  <package id="System.Interactive.Async" version="3.2.0" targetFramework="net47" />
  <package id="System.IO" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Linq" version="4.3.0" targetFramework="net47" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net47" />
  <package id="System.Net.Http" version="4.3.0" targetFramework="net47" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="net47" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="net47" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net47" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net47" />
</packages>

Please advise us immediately so we can migrate from Google Adwords to Google Ads ASAP so we wouldn't have to worry about the upcoming sunsets for the previous versions. Thank you!

**Comment by jaycatapang** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Google.Ads.GoogleAds" version="1.0.0" targetFramework="net47" />
  <package id="Google.Api.CommonProtos" version="1.5.0" targetFramework="net47" />
  <package id="Google.Api.Gax" version="2.6.0" targetFramework="net47" />
  <package id="Google.Api.Gax.Grpc" version="2.6.0" targetFramework="net47" />
  <package id="Google.Apis" version="1.38.0" targetFramework="net47" />
  <package id="Google.Apis.Auth" version="1.38.0" targetFramework="net47" />
  <package id="Google.Apis.Core" version="1.38.0" targetFramework="net47" />
  <package id="Google.LongRunning" version="1.1.0" targetFramework="net47" />
  <package id="Google.Protobuf" version="3.6.1" targetFramework="net47" />
  <package id="Grpc.Auth" version="1.18.0" targetFramework="net47" />
  <package id="Grpc.Core" version="1.19.0" targetFramework="net47" />
  <package id="Grpc.Core.Api" version="1.19.0" targetFramework="net47" />
  <package id="Microsoft.Extensions.Configuration" version="1.1.2" targetFramework="net47" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="1.1.2" targetFramework="net47" />
  <package id="Microsoft.Extensions.Primitives" version="1.1.1" targetFramework="net47" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net47" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="net47" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net47" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net47" />
  <package id="System.Collections" version="4.3.0" targetFramework="net47" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net47" />
  <package id="System.Console" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net47" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net47" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net47" />
  <package id="System.Interactive.Async" version="3.2.0" targetFramework="net47" />
  <package id="System.IO" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Linq" version="4.3.0" targetFramework="net47" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net47" />
  <package id="System.Net.Http" version="4.3.0" targetFramework="net47" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="net47" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="net47" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net47" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net47" />
</packages>
`

**Comment by AnashOommen** [comment]
Just so I get this correct, the issue is when you are making a class library, right? All kind of conflicts happen?

To answer your other question, yes, you can migrate to Google Ads API at your earliest convenience. I’ll start looking into replicating this at my end.

**Comment by jaycatapang** [comment]
Yes. Somehow the problem arises when creating a class library. We deploy the build to a web server by the way and we just do a POST request.

Yes we are doing that as we speak. But we got stuck due to the said problem.

Thank you!

**Comment by AnashOommen** [comment]
Here's an sln that shows various types of projects. MainLibrary has dependency on Google.Ads.GoogleAds v1.1.0 => Grpc.Core 1.19.0 and Google.Cloud.Speech.V1 => Grpc.Core 1.18.0. The dependency resolution is done in the binary's App.config.

[ChainedDependencies.zip](https://github.com/googleads/google-ads-dotnet/files/3092384/ChainedDependencies.zip)

**Comment by brynnborton** [comment]
Hi Anash 

did this issue get resolved we are getting the same error i.e. the nuget package installs 1.3.9 of Google.Apis.Auth by default.  

We have a binding redirect in the app.config as follows 

`<dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.39.0.0" newVersion="1.39.0.0" />
      </dependentAssembly>
`
For some reason it looks as if it is trying to call version 1.21.    This is a clean class library in which we simply added google ads via nuget.
