### ISSUE TITLE
How to set date range as ALL_TIME in google ads api

### ISSUE THREAD

**Issue by Swapygit** [googleads/google-ads-dotnet#64]
Hi, I am fetching campaign level data using google ads api. What value of date range should I set so that I can get the "ALL_TIME" campaign data.

Kindly help

**Comment by AnashOommen** [comment]
You could do `select campaign.name, metrics.clicks, metrics.impressions from campaign`

If you want the data segmented by date, then you need to do

`select campaign.name, metrics.clicks, metrics.impressions, segments.date from campaign where segments.date >= '2019-01-01' AND segments.date <= '2019-01-31'`

There's no equivalent of `ALL_TIME` in this case. The date range can be large, but ranges have to be bound in the query. https://developers.google.com/google-ads/api/docs/query/date-ranges

**Comment by Swapygit** [comment]
Hi @AnashOommen 

But then we need to specify the start date of every customer id for fetching the All time data which is not a feasible solution. What can be the potential solution for that.

**Comment by AnashOommen** [comment]
For now, the only thing I can think of is to set a high enough date.(Jan 1, 2000) for instance. Though, you run the risk of getting Deadline exceeded errors with that approach.

I can file an FR with the product team.
