### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by bbatton** [googleads/google-ads-dotnet#66]
I have previously been using the googleads-dotnet-lib library to make calls to google ads without issue. After switching to a new dotnet core project I use my previous credentials set up for the googleads-dotnet-lib library the google-ads-dotnet library throws the following error. 

'Google.Ads.GoogleAds.V1.Errors.GoogleAdsException; in System.Private.CoreLib.dll ("Status (StatusCode=PermissionDenied, Detail="Google Ads API has not been used in the project before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/googleads.googleapis.com/overview?project= then retry. If you enabled this API recently, wait a few minutes for the action to propagate tor our systems and retry.")")

I omitted the project number in the above however when I try to visit that page it errors out. Also when I try to add the library to my project in the developer's console I get the following error on the page "API solution not found with service name: googleads.googleapis.com".

Can I not use my OAuth credentials from the previous library and how do I get this setup in this case?

**Comment by AnashOommen** [comment]
Hi,

1. You can enable the project in Google Developer console, but I recommend turning off any AdBlockers. They've known to cause errors when enabling Google Ads API in the console.

2. Once you do that, Wait for 5 mins and try making the API call again, and it should work.

**Comment by bbatton** [comment]
Thanks for the reply, that seems to have done the trick. On a side note is there a call in this library to grab all customer accounts retrieving customer id and name? I browsed through the library and I haven't seen a call that is doing that yet.
