### ISSUE TITLE
Can't Grab Managed Customers

### ISSUE THREAD

**Issue by bbatton** [googleads/google-ads-dotnet#68]
The endpoint Service.ListAccessibleCustomersAsync(request) under the CustomerServiceClient service will only return the manager customer id as a response instead of the customer id's that the manager has access to. Any insight would be greatly appreciated, thanks as always.

**Comment by AnashOommen** [comment]
ListAccessibleCustomers is meant to return you all the customerids your login email (authenticated user) has access to. You’d then set one of these customerids in the login customer id header to make the remaining calls.

It’s the equivalent of the account picker in Google Ads UI.

If you are looking for the equivalent of getaccounthierarchy, you need to look at CustomerClient.

https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.resources#google.ads.googleads.v1.resources.CustomerClient
