### ISSUE TITLE
GoogleAdsServiceClient

### ISSUE THREAD

**Issue by bbatton** [googleads/google-ads-dotnet#69]
SearchAsync doesn't have a GetAwaiter method so you can't use await making the call run synchronously

**Comment by AnashOommen** [comment]
Why not use Search instead? Also, can it be awaited on without using getawaiter?

(I know there’s a way, since sync methods are implemented as await on async methods. Will check later once I am on a computer)

**Comment by bbatton** [comment]
I am using Search in the time being. VS says it can't be awaited without it, if you know how to do it without await can you send me doc about it. Thanks

**Comment by AnashOommen** [comment]
Something like this should work:

```c#
GoogleAdsClient client = new GoogleAdsClient();

GoogleAdsServiceClient searchService = client.GetService(Services.V1.GoogleAdsService);

SearchGoogleAdsRequest request = new SearchGoogleAdsRequest() {
  CustomerId = "1234567890",
  Query = "Select campaign.name, metrics.clicks from campaign during YESTERDAY",
};

PagedAsyncEnumerable<SearchGoogleAdsResponse, GoogleAdsRow> response =
    searchService.SearchAsync("1234567890", 
    "Select campaign.name, metrics.clicks from campaign during YESTERDAY");

await response.ForEachAsync((GoogleAdsRow row) =>
{
  // Do something with each item
});
```
