### ISSUE TITLE
MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Anonymous'

### ISSUE THREAD

**Issue by Swapygit** [googleads/google-ads-dotnet#70]
Hi Team,

I am trying to link to google adwords account using Oauth2 in C# .net . However, I am getting the following error, 

**MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'OAuth realm="https://accounts.google.com/OAuthGetRequestToken"'. [Returned while handling POST Request]**

I had a communication regarding this with the google adwords support team. They had following reply for this

**It looks like the issue is specific to the client library that you're using. Could you please post your concern on the Github issue tracker so the library owners can assist you on this**

Kindly suggest what can I do to resolve the exception

**Comment by AnashOommen** [comment]
Hi Swapygit,

That error seems related to WCF (See http://ddkonline.blogspot.com/2009/11/fix-http-request-is-unauthorized-with.html). The client library uses HTTPClient for OAuth2, and a custom HTTP2 library (unrelated to .NET SDK classes) for making GRPC calls. So it is very unlikely that this error has anything to do with the client library itself.

My guess is that you have some WCF-related setting that's broad and interfering with the OAuth2 HTTP calls. That, unfortunately, is beyond my area of expertise. If you can share additional configuration details, I can try to figure out what's wrong.

**Comment by Swapygit** [comment]
Hi @AnashOommen ,

I went through the link you provided me but did not get any solution for my problem.
Do I need to do any changes in the Web config of my application.

**Comment by danpillay87** [comment]
Hi @Swapygit can you please provide some more detailed outline of the webconfig you are currently using.

**Comment by Swapygit** [comment]
Hi @AnashOommen 
We are not using WCF related service for making a call to adwords API linking. We are using the google.adwords library.

Please find the below details regarding the web config.

<add key="DeveloperToken" value="lm25z688dVdqw-QXn9UrNw" />
<add key="OAuth2ClientId" value="551007376892-lqjhddrrt6nhrhha0af7vdiooqiltcjr.apps.googleusercontent.com" />
    <add key="OAuth2ClientSecret" value="FmgeWMleF0Vuc3NGiCNsRIRn" />
	<add key="OAuth2RefreshToken" value="1/fKmDLpHBpomBO2-bKtdKYvgV9tVGT0EpvSuSeyW6S1wMEudVrK5jSpoR30zcRFq6" />

**Comment by AnashOommen** [comment]
Is that the only thing in your Web.config? Can you mail your full Web.config to googleadsapi-support@google.com and cc anash@google.com so I can start a private discussion with you?

**Comment by Swapygit** [comment]
Hi @AnashOommen 
This issue has re occurred when the user tried to link from our Mobile App.

Can you help in sorting this.
