### ISSUE TITLE
Response Times

### ISSUE THREAD

**Issue by bbatton** [googleads/google-ads-dotnet#71]
I have been having an extreme delay with the internal parsing of requests to the API. I don't think it is necessarily the time it takes the route to process the query but I am unsure. It is taking 1 - 2 minutes for a request to go out and then to be internally parsed by the library before writing to console. The googleads-dotnet library, however, is almost instant with the same query. Is this normal behavior for this library or is this just a symptom of something on my end? I have listed a code example of an example request that takes this long below.

**Comment by bbatton** [comment]
` public static async Task<IEnumerable<SearchGoogleAdsResponse>> GetCampaigns(GoogleAdsSettings settings)
        {
            var AdService = new GoogleAdsClient(SetupAuth(settings));
            PagedEnumerable<SearchGoogleAdsResponse, GoogleAdsRow> searchPagedResponse = null;
            GoogleAdsServiceClient Service = AdService.GetService(Services.V1.GoogleAdsService);
            SearchGoogleAdsRequest request = new SearchGoogleAdsRequest()
            {
                PageSize = PAGE_SIZE,
                Query = @"SELECT
                            campaign.id,
                            campaign.name,
                            campaign.status,
                            campaign.serving_status,
                            campaign.network_settings.target_content_network,
                            campaign.network_settings.target_google_search,
                            campaign.network_settings.target_search_network,
                            campaign.network_settings.target_partner_search_network,
                            campaign.start_date,
                            campaign.end_date,
                            campaign.campaign_budget,
                            campaign.advertising_channel_type
                        FROM campaign
                        ORDER BY campaign.id",
                CustomerId = "3267541714"
            };

            try
            {
               searchPagedResponse = Service.Search(request);
            }
            catch (GoogleAdsException e)
            {
                await ReportError(e);
            }

            return searchPagedResponse.AsRawResponses();
        }`

**Comment by bbatton** [comment]
public static async Task<IEnumerable<SearchGoogleAdsResponse>> GetCampaigns(GoogleAdsSettings settings)
        {
            var AdService = new GoogleAdsClient(SetupAuth(settings));
            PagedEnumerable<SearchGoogleAdsResponse, GoogleAdsRow> searchPagedResponse = null;
            GoogleAdsServiceClient Service = AdService.GetService(Services.V1.GoogleAdsService);
            SearchGoogleAdsRequest request = new SearchGoogleAdsRequest()
            {
                PageSize = PAGE_SIZE,
                Query = @"SELECT
                            campaign.id,
                            campaign.name,
                            campaign.status,
                            campaign.serving_status,
                            campaign.network_settings.target_content_network,
                            campaign.network_settings.target_google_search,
                            campaign.network_settings.target_search_network,
                            campaign.network_settings.target_partner_search_network,
                            campaign.start_date,
                            campaign.end_date,
                            campaign.campaign_budget,
                            campaign.advertising_channel_type
                        FROM campaign
                        ORDER BY campaign.id",
                CustomerId = "3267541714"
            };

            try
            {
               searchPagedResponse = Service.Search(request);
            }
            catch (GoogleAdsException e)
            {
                await ReportError(e);
            }

            return searchPagedResponse.AsRawResponses();
        }

**Comment by bbatton** [comment]
Task<IEnumerable<SearchGoogleAdsResponse>> for some reason keeps getting changed to Task<IEnumerable> when I posted above

**Comment by bbatton** [comment]
the return keeps getting edited when I comment just an FYI is is returning an IEnumerable of SearchGoogleAdsResponse

**Comment by AnashOommen** [comment]
I can't replicate this at my end, it works in a few seconds. Is there a zipped project (without credentials) you can share so I can try to replicate?

**Comment by AnashOommen** [comment]
Hi Brandon,

I am closing this bug for now as non-replicable, but feel free to reopen whenever you have additional details to share.
