### ISSUE TITLE
How to generate report with zero impressions along with segments.Date  ?

### ISSUE THREAD

**Issue by devipriya2019** [googleads/google-ads-dotnet#73]

**Comment by devipriya2019** [comment]
The query listed below , returns rows containing non-zero values for "metrics.impressions" column. However if I remove "segments.date" from the select statement , all the records , including ones that contain zero "metrics.impressions" value are returned.

`string query =
                $@"SELECT
	                 ad_group_ad.ad.id,
	                 campaign.id,
	                 segments.date,
	                 metrics.impressions,
	                 metrics.clicks,
	                 metrics.cost_micros,
                         metrics.average_position,
                FROM
	                ad_group_ad
                WHERE segments.date BETWEEN '2019-04-17' AND '2019-04-28'  `

I want to retrieve all the "metrics.impressions" rows by "segments.date". What should I do to modify the query listed above to return zero "metrics.impressions" rows along with "segments.date" value?

**Comment by AnashOommen** [comment]
I don’t think it can be done, IIRC zero impression rows are incompatible with date segments even in the old API.

Could you post this question on https://groups.google.com/forum/m/#!forum/adwords-api also, sonce this question is not specific to .NET library?
