### ISSUE TITLE
 The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'OAuth realm="https://accounts.google.com/OAuthGetRequestToken"'. [Returned while handling POST Request

### ISSUE THREAD

**Issue by Swapygit** [googleads/google-ads-dotnet#77]
Hi Team,

I am trying to fetch customer information using google adwords api version v201809 in C# .NET
 But sometimes I get the following error

" The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'OAuth realm="https://accounts.google.com/OAuthGetRequestToken"'. [Returned while handling POST Request"

What is the root cause of this error. Please help me with this.

**Comment by jradcliff** [comment]
Hi,

Please see my colleague's response on the other issue you opened:

https://github.com/googleads/google-ads-dotnet/issues/70

If you still have questions from there, please reopen that issue and provide the additional details @AnashOommen requested.

Thanks,
Josh, Google Ads API Team
