### ISSUE TITLE
Client not working in Net Core Web API context

### ISSUE THREAD

**Issue by jordan-sightly** [googleads/google-ads-dotnet#80]
I have created a net core console app that uses the client and successfully retrieves data.  However, when I add a net core web api project and call the same logic, all queries time out and return a "TRANSIENT_FAILURE" message.  This only happens if I run the web API and make http calls into it -- running the console app still works.

**Comment by AnashOommen** [comment]
I suspect this is due to https://github.com/googleads/google-ads-dotnet/issues/59. Could you see if the recommended fix on that bug works for you?

**Comment by jordan-sightly** [comment]
Thank you for the quick response.  You were correct... and I had that code in the console app Program.cs but it was missed in the web API.

Is there an ETA on when that fix will be released in the client?
