### ISSUE TITLE
Connected TV device stats not working:  v2.1.0 client (API 1.3)

### ISSUE THREAD

**Issue by jordan-sightly** [googleads/google-ads-dotnet#84]
Connected TV device stats are not working in the latest release.  When I query by device, I don't get a connected TV result back, but the Desktop result appears to be the sum of Desktop and Connected TV.

**Comment by AnashOommen** [comment]
Could you pls post on the forum? https://groups.google.com/forum/#!forum/adwords-api

This is an API-specific issue and you'd getter faster responses on the forum.
