### ISSUE TITLE
Failed to exchange authorization code for access token

### ISSUE THREAD

**Issue by Swapygit** [googleads/google-ads-dotnet#87]
Hi Team,

We are managing our clients google ads account using our Manager account (527-708-3201). When our client to connect to our Manager account using our mobile app (**adwords API**) I am getting the following error.

Failed to exchange authorization code for access token.

Kindly tell me what is the reason behind this error. How can I resolve this.

**Comment by AnashOommen** [comment]
Hi Swapygit,

You need to look at the response returned by the server to understand why. If you turn on logging, the error logs get captured in the details log. Another option is to use Fiddler to capture these logs, as explained here: https://github.com/googleads/googleads-dotnet-lib/wiki/How-to-capture-SOAP-messages#option-2-use-fiddler

**Comment by AnashOommen** [comment]
I'm marking this issue as not replicable. Feel free to open a new issue if this persists.
